"""Structured data privacy package for section 4.2.

Intended contents include column classification, k-anonymity, l-diversity,
t-closeness, and differential privacy capabilities.
"""

from .discharge_summary import (
    REQUIRED_DISCHARGE_SLOTS,
    DischargeSlotName,
    DischargeSummary,
    DischargeSummarySection,
    canonical_discharge_slot,
    structure_discharge_summary,
)
from .flowsheet import (
    FLOWSHEET_ADVISORY,
    Flowsheet,
    ParameterSeries,
    TimeSeriesPoint,
    structure_flowsheet,
)
from .generalize import (
    DEFAULT_TARGET_K,
    MANIFEST_SCHEMA_VERSION,
    MODEL_K_ANON,
    SUPPORTED_MODELS,
    AnonymizationError,
    AnonymizationResult,
    anonymize_table,
)
from .hierarchies import (
    COLUMN_TYPE_AGE,
    COLUMN_TYPE_DATE,
    COLUMN_TYPE_ZIP,
    HIERARCHY_SCHEMA_VERSION,
    SUPPORTED_COLUMN_TYPES,
    GeneralizationLevel,
    Hierarchy,
    HierarchyError,
    build_enforcement_hierarchies,
    describe_level,
    generalize_value,
    get_hierarchy,
    max_level,
    to_enforce_kanon_hierarchy,
)
from .lab_panels import (
    LAB_PANEL_ADVISORY,
    PANEL_ORDER,
    AnalyteRow,
    LabPanel,
    canonical_analyte,
    parse_lab_report,
    structure_lab_panels,
)
from .qi_detect import (
    ROLE_DIRECT_ID,
    ROLE_FREE_TEXT,
    ROLE_INTERNAL_LINKAGE,
    ROLE_QUASI_ID,
    ROLE_SAFE,
    ROLE_SENSITIVE,
    DiscoveryConfigurationError,
    scan_table,
)
from .relational import (
    RELATIONAL_ADVISORY,
    ColumnRef,
    DanglingForeignKeyError,
    DateColumn,
    ForeignKey,
    KeySpace,
    RelationalDeidentificationResult,
    RelationalSchema,
    RelationalSchemaError,
    SurrogateManifest,
    deidentify_linked_tables,
)
from .scan import (
    ColumnClassification,
    ColumnRole,
    RoleOverrideError,
    TableRoleScan,
)
from .scan import scan_table as scan_column_roles
from .table_io import SUPPORTED_TABLE_SUFFIXES, read_table, write_table
from .tables import (
    TABLE_ADVISORY,
    Table,
    TableCell,
    TableToken,
    cell_at,
    structure_table,
)

__all__ = [
    "COLUMN_TYPE_AGE",
    "COLUMN_TYPE_DATE",
    "COLUMN_TYPE_ZIP",
    "DEFAULT_TARGET_K",
    "FLOWSHEET_ADVISORY",
    "HIERARCHY_SCHEMA_VERSION",
    "LAB_PANEL_ADVISORY",
    "MANIFEST_SCHEMA_VERSION",
    "MODEL_K_ANON",
    "PANEL_ORDER",
    "RELATIONAL_ADVISORY",
    "REQUIRED_DISCHARGE_SLOTS",
    "SUPPORTED_COLUMN_TYPES",
    "SUPPORTED_MODELS",
    "AnalyteRow",
    "AnonymizationError",
    "AnonymizationResult",
    "ColumnClassification",
    "ColumnRef",
    "ColumnRole",
    "DanglingForeignKeyError",
    "DateColumn",
    "DischargeSlotName",
    "DischargeSummary",
    "DischargeSummarySection",
    "DiscoveryConfigurationError",
    "Flowsheet",
    "ForeignKey",
    "GeneralizationLevel",
    "Hierarchy",
    "HierarchyError",
    "KeySpace",
    "LabPanel",
    "ParameterSeries",
    "ROLE_DIRECT_ID",
    "ROLE_FREE_TEXT",
    "ROLE_INTERNAL_LINKAGE",
    "ROLE_QUASI_ID",
    "ROLE_SAFE",
    "ROLE_SENSITIVE",
    "RelationalDeidentificationResult",
    "RelationalSchema",
    "RelationalSchemaError",
    "RoleOverrideError",
    "SUPPORTED_TABLE_SUFFIXES",
    "SurrogateManifest",
    "TABLE_ADVISORY",
    "Table",
    "TableCell",
    "TableToken",
    "TableRoleScan",
    "TimeSeriesPoint",
    "anonymize_table",
    "build_enforcement_hierarchies",
    "canonical_analyte",
    "cell_at",
    "canonical_discharge_slot",
    "deidentify_linked_tables",
    "describe_level",
    "generalize_value",
    "get_hierarchy",
    "max_level",
    "parse_lab_report",
    "read_table",
    "scan_column_roles",
    "scan_table",
    "structure_discharge_summary",
    "structure_flowsheet",
    "structure_lab_panels",
    "structure_table",
    "to_enforce_kanon_hierarchy",
    "write_table",
]
