"""Clinical concept normalization with pluggable terminology backends."""

from __future__ import annotations

from .backend import (
    SYNTHETIC_CODE_SYSTEMS,
    SYNTHETIC_CONCEPTS,
    BackendIdentity,
    CodeSystemMetadata,
    SyntheticTerminologyBackend,
    TerminologyBackend,
    TerminologyConcept,
    normalize_surface,
    validate_backend_identity,
)
from .cache import (
    ConceptNormalizationCache,
    NormalizationCacheStats,
    make_normalization_cache_key,
)
from .chinese import (
    CHINESE_DRUG_SYSTEM,
    CHINESE_ICD_10_SYSTEM,
    CHINESE_TERMINOLOGY_DISCLAIMER,
    CHINESE_TERMINOLOGY_VOCABULARY_NOTE,
    ChineseTerminologyDictionary,
    ChineseTerminologyEntry,
    ChineseTerminologyError,
    ChineseTerminologyGrounder,
    ChineseTerminologyLicenseError,
    ChineseTerminologyMatch,
    ChineseTerminologyPathError,
    load_chinese_terminology_dictionary,
    normalize_chinese_clinical_surface,
)
from .india import (
    INDIAN_CLINICAL_ABBREVIATIONS,
    INDIAN_CLINICAL_NORMALIZATION_VERSION,
    IndianClinicalNormalization,
    normalize_indian_clinical_abbreviation,
    normalize_indian_clinical_entities,
    normalize_indian_clinical_surface,
)
from .india_terminology import (
    AYUSH,
    DEFAULT_AYUSH_SYSTEM_URI,
    DEFAULT_INDIAN_DRUG_SYSTEM_URI,
    INDIA_TERMINOLOGY_KINDS,
    INDIAN_DRUG,
    GroundedIndiaTerm,
    IndiaTerminologyDictionary,
    IndiaTerminologyError,
    IndiaTerminologyFormatError,
    IndiaTerminologyKind,
    IndiaTerminologyLoader,
    IndiaTerminologyLoadResult,
    TerminologySkipNotice,
    UserSuppliedIndiaTerminology,
    normalize_india_terminology_surface,
)
from .ranker import (
    SYNTHETIC_GOLD_SET,
    CandidateProvenance,
    ConceptNormalizer,
    NormalizationEvaluationResult,
    NormalizationGoldCase,
    RankedConcept,
    evaluate_normalization_gold,
    generate_query_variants,
)

__all__ = [
    "BackendIdentity",
    "AYUSH",
    "CHINESE_DRUG_SYSTEM",
    "CHINESE_ICD_10_SYSTEM",
    "CHINESE_TERMINOLOGY_DISCLAIMER",
    "CHINESE_TERMINOLOGY_VOCABULARY_NOTE",
    "CandidateProvenance",
    "ChineseTerminologyDictionary",
    "ChineseTerminologyEntry",
    "ChineseTerminologyError",
    "ChineseTerminologyGrounder",
    "ChineseTerminologyLicenseError",
    "ChineseTerminologyMatch",
    "ChineseTerminologyPathError",
    "CodeSystemMetadata",
    "ConceptNormalizationCache",
    "ConceptNormalizer",
    "DEFAULT_AYUSH_SYSTEM_URI",
    "DEFAULT_INDIAN_DRUG_SYSTEM_URI",
    "GroundedIndiaTerm",
    "INDIA_TERMINOLOGY_KINDS",
    "INDIAN_CLINICAL_ABBREVIATIONS",
    "INDIAN_CLINICAL_NORMALIZATION_VERSION",
    "INDIAN_DRUG",
    "IndianClinicalNormalization",
    "IndiaTerminologyDictionary",
    "IndiaTerminologyError",
    "IndiaTerminologyFormatError",
    "IndiaTerminologyKind",
    "IndiaTerminologyLoadResult",
    "IndiaTerminologyLoader",
    "NormalizationCacheStats",
    "NormalizationEvaluationResult",
    "NormalizationGoldCase",
    "RankedConcept",
    "SYNTHETIC_CODE_SYSTEMS",
    "SYNTHETIC_CONCEPTS",
    "SYNTHETIC_GOLD_SET",
    "SyntheticTerminologyBackend",
    "TerminologySkipNotice",
    "TerminologyBackend",
    "TerminologyConcept",
    "UserSuppliedIndiaTerminology",
    "evaluate_normalization_gold",
    "generate_query_variants",
    "load_chinese_terminology_dictionary",
    "make_normalization_cache_key",
    "normalize_chinese_clinical_surface",
    "normalize_indian_clinical_abbreviation",
    "normalize_indian_clinical_entities",
    "normalize_indian_clinical_surface",
    "normalize_surface",
    "normalize_india_terminology_surface",
    "validate_backend_identity",
]
