"""Clinical concept normalization with pluggable terminology backends."""

from __future__ import annotations

from .backend import (
    SYNTHETIC_CODE_SYSTEMS,
    SYNTHETIC_CONCEPTS,
    BackendIdentity,
    CodeSystemMetadata,
    SyntheticTerminologyBackend,
    TerminologyBackend,
    TerminologyConcept,
    normalize_surface,
    validate_backend_identity,
)
from .cache import (
    ConceptNormalizationCache,
    NormalizationCacheStats,
    make_normalization_cache_key,
)
from .chinese import (
    CHINESE_DRUG_SYSTEM,
    CHINESE_ICD_10_SYSTEM,
    CHINESE_TERMINOLOGY_DISCLAIMER,
    CHINESE_TERMINOLOGY_VOCABULARY_NOTE,
    ChineseTerminologyDictionary,
    ChineseTerminologyEntry,
    ChineseTerminologyError,
    ChineseTerminologyGrounder,
    ChineseTerminologyLicenseError,
    ChineseTerminologyMatch,
    ChineseTerminologyPathError,
    load_chinese_terminology_dictionary,
    normalize_chinese_clinical_surface,
)
from .ranker import (
    SYNTHETIC_GOLD_SET,
    CandidateProvenance,
    ConceptNormalizer,
    NormalizationEvaluationResult,
    NormalizationGoldCase,
    RankedConcept,
    evaluate_normalization_gold,
    generate_query_variants,
)

__all__ = [
    "BackendIdentity",
    "CHINESE_DRUG_SYSTEM",
    "CHINESE_ICD_10_SYSTEM",
    "CHINESE_TERMINOLOGY_DISCLAIMER",
    "CHINESE_TERMINOLOGY_VOCABULARY_NOTE",
    "CandidateProvenance",
    "ChineseTerminologyDictionary",
    "ChineseTerminologyEntry",
    "ChineseTerminologyError",
    "ChineseTerminologyGrounder",
    "ChineseTerminologyLicenseError",
    "ChineseTerminologyMatch",
    "ChineseTerminologyPathError",
    "CodeSystemMetadata",
    "ConceptNormalizationCache",
    "ConceptNormalizer",
    "NormalizationCacheStats",
    "NormalizationEvaluationResult",
    "NormalizationGoldCase",
    "RankedConcept",
    "SYNTHETIC_CODE_SYSTEMS",
    "SYNTHETIC_CONCEPTS",
    "SYNTHETIC_GOLD_SET",
    "SyntheticTerminologyBackend",
    "TerminologyBackend",
    "TerminologyConcept",
    "evaluate_normalization_gold",
    "generate_query_variants",
    "load_chinese_terminology_dictionary",
    "make_normalization_cache_key",
    "normalize_chinese_clinical_surface",
    "normalize_surface",
    "validate_backend_identity",
]
