"""Clinical document understanding package for section 4.2.

Intended contents include sections.py, context.py, grounding.py, relations.py,
sdoh.py, and FHIR/OMOP exporters.
"""

from .context import (
    AFFIRMED,
    CERTAIN,
    CERTAINTY_VALUES,
    HISTORICAL,
    HYPOTHETICAL,
    NEGATED,
    NEGATION_VALUES,
    RECENT,
    TEMPORALITY_VALUES,
    UNCERTAIN,
    Certainty,
    ClinicalAssertion,
    ClinicalContextResult,
    Negation,
    assert_context_axes,
    resolve_negation,
    resolve_span_context,
    resolve_temporality,
    resolve_uncertainty,
)
from .lab_values import (
    LAB_FLAG_ADVISORY,
    AbnormalFlag,
    ReferenceRange,
    derive_abnormal_flag,
    parse_reference_range,
)
from .vital_signs import (
    VITAL_SIGNS_ADVISORY,
    VitalKind,
    VitalSignComponent,
    VitalSignComponentKind,
    VitalSignNumber,
    VitalSignResult,
    empty_vital_sign_result,
    structure_vital_sign,
)

__all__ = [
    "AFFIRMED",
    "NEGATED",
    "NEGATION_VALUES",
    "Negation",
    "ClinicalContextResult",
    "ClinicalAssertion",
    "resolve_negation",
    "resolve_span_context",
    "assert_context_axes",
    "RECENT",
    "HISTORICAL",
    "HYPOTHETICAL",
    "TEMPORALITY_VALUES",
    "resolve_temporality",
    "Certainty",
    "CERTAIN",
    "UNCERTAIN",
    "CERTAINTY_VALUES",
    "resolve_uncertainty",
    "AbnormalFlag",
    "ReferenceRange",
    "LAB_FLAG_ADVISORY",
    "parse_reference_range",
    "derive_abnormal_flag",
    "VitalKind",
    "VitalSignComponentKind",
    "VitalSignNumber",
    "VitalSignComponent",
    "VitalSignResult",
    "VITAL_SIGNS_ADVISORY",
    "empty_vital_sign_result",
    "structure_vital_sign",
]
