"""Clinical document understanding package for section 4.2.

Intended contents include sections.py, context.py, grounding.py, relations.py,
sdoh.py, and FHIR/OMOP exporters.
"""

from .context import (
    AFFIRMED,
    CANONICAL_SECTION_LABELS,
    CERTAIN,
    CERTAINTY_VALUES,
    FAMILY_EXPERIENCER,
    HISTORICAL,
    HYPOTHETICAL,
    NEGATED,
    NEGATION_VALUES,
    PATIENT_EXPERIENCER,
    RECENT,
    SECTION_CONTEXT_PRIORS,
    SECTION_LABEL_ALIASES,
    TEMPORALITY_VALUES,
    UNCERTAIN,
    Certainty,
    ClinicalAssertion,
    ClinicalContextResult,
    Negation,
    apply_section_context,
    assert_context_axes,
    resolve_negation,
    resolve_span_context,
    resolve_temporality,
    resolve_uncertainty,
)
from .lab_values import (
    LAB_FLAG_ADVISORY,
    AbnormalFlag,
    ReferenceRange,
    derive_abnormal_flag,
    parse_reference_range,
)

__all__ = [
    "AFFIRMED",
    "NEGATED",
    "NEGATION_VALUES",
    "Negation",
    "ClinicalContextResult",
    "ClinicalAssertion",
    "resolve_negation",
    "apply_section_context",
    "resolve_span_context",
    "assert_context_axes",
    "RECENT",
    "HISTORICAL",
    "HYPOTHETICAL",
    "TEMPORALITY_VALUES",
    "PATIENT_EXPERIENCER",
    "FAMILY_EXPERIENCER",
    "CANONICAL_SECTION_LABELS",
    "SECTION_LABEL_ALIASES",
    "SECTION_CONTEXT_PRIORS",
    "resolve_temporality",
    "Certainty",
    "CERTAIN",
    "UNCERTAIN",
    "CERTAINTY_VALUES",
    "resolve_uncertainty",
    "AbnormalFlag",
    "ReferenceRange",
    "LAB_FLAG_ADVISORY",
    "parse_reference_range",
    "derive_abnormal_flag",
]
