"""Execution planning contracts for on-device vision workloads."""

from __future__ import annotations

from .resource_planner import (
    CLOUD_FALLBACK_ALLOWED,
    MAX_ACTIVATION_BYTES_PER_PIXEL,
    MAX_CACHE_BYTES_PER_TILE,
    MAX_DEVICE_TIERS,
    MAX_FRAMES,
    MAX_MEMORY_BYTES,
    MAX_MODEL_PARAMETERS,
    MAX_OUTPUT_BYTES,
    MAX_PIXEL_SIDE,
    MAX_TILE_SIZE,
    MAX_WEIGHT_BYTES_PER_PARAMETER,
    RESOURCE_PLAN_REASON_CODES,
    RESOURCE_PLAN_VERSION,
    VLM_TIER_DESKTOP_V1,
    VLM_TIER_MOBILE_V1,
    DeviceTier,
    PreprocessingPlan,
    ResourcePlanOutcome,
    TierCandidate,
    VLMExecutionPlan,
    VLMExecutionPolicy,
    VLMResourceEstimate,
    VLMResourcePlannerError,
    plan_vlm_execution,
)

__all__ = [
    "CLOUD_FALLBACK_ALLOWED",
    "MAX_ACTIVATION_BYTES_PER_PIXEL",
    "MAX_CACHE_BYTES_PER_TILE",
    "MAX_DEVICE_TIERS",
    "MAX_FRAMES",
    "MAX_MEMORY_BYTES",
    "MAX_MODEL_PARAMETERS",
    "MAX_OUTPUT_BYTES",
    "MAX_PIXEL_SIDE",
    "MAX_TILE_SIZE",
    "MAX_WEIGHT_BYTES_PER_PARAMETER",
    "RESOURCE_PLAN_REASON_CODES",
    "RESOURCE_PLAN_VERSION",
    "VLM_TIER_DESKTOP_V1",
    "VLM_TIER_MOBILE_V1",
    "DeviceTier",
    "PreprocessingPlan",
    "ResourcePlanOutcome",
    "TierCandidate",
    "VLMExecutionPlan",
    "VLMExecutionPolicy",
    "VLMResourceEstimate",
    "VLMResourcePlannerError",
    "plan_vlm_execution",
]
