"""Tests for the declarative generalization function family.

All fixtures are synthetic and generated algorithmically; no real values are
used. Boundary values called out by the task (age 0/89/90/120, 5-digit and
7-character postcodes, leap-day dates) are covered explicitly alongside a wider
formula-generated grid.
"""

from __future__ import annotations

import re
from datetime import date, datetime, timedelta

import pytest

from openmed.core.date_shift import stable_offset_for
from openmed.risk import enforce_kanon
from openmed.structured import (
    COLUMN_TYPE_AGE,
    COLUMN_TYPE_CLINICAL_CODE,
    COLUMN_TYPE_DATE,
    COLUMN_TYPE_ZIP,
    GeneralizationLevel,
    Hierarchy,
    HierarchyError,
    build_enforcement_hierarchies,
    describe_level,
    generalize_value,
    get_hierarchy,
    max_level,
    to_enforce_kanon_hierarchy,
)
from openmed.structured.hierarchies import (
    AGE_MAX,
    AGE_MIN_BAND_WIDTH,
    AGE_TOP_BAND,
    AGE_TOP_THRESHOLD,
    HIERARCHY_SCHEMA_VERSION,
    SUPPORTED_COLUMN_TYPES,
    SUPPRESSED,
)

SECRET = "unit-test-secret-value"

# --------------------------------------------------------------------------- #
# Synthetic, algorithmically generated fixtures                               #
# --------------------------------------------------------------------------- #
AGE_BOUNDARIES = (0, 89, 90, 120)
AGE_GRID = sorted({*AGE_BOUNDARIES, *range(0, AGE_MAX + 1, 7)})

# Five-digit ZIPs and seven-character alphanumeric postcodes, both by formula.
_ALNUM = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
ZIP5_GRID = tuple(f"{(i * 3607) % 100000:05d}" for i in range(12))
POSTCODE7_GRID = tuple(
    "".join(_ALNUM[(i * (j + 5) + 7) % len(_ALNUM)] for j in range(7))
    for i in range(12)
)
ZIP_GRID = ZIP5_GRID + POSTCODE7_GRID

# Regular dates plus leap days generated by formula.
DATE_GRID = tuple(
    (date(2019, 1, 1) + timedelta(days=i * 53)).isoformat() for i in range(12)
) + ("2024-02-29", "2020-02-29", "2000-02-29")
CLINICAL_CODE_GRID = ("A1", "A2", "44054006")


# --------------------------------------------------------------------------- #
# Specificity measurement for the monotonicity gate                           #
# --------------------------------------------------------------------------- #
def _age_specificity(label: str) -> float:
    """Coarseness of an age output: larger means coarser (less specific)."""
    if label == SUPPRESSED:
        return float("inf")
    if label == AGE_TOP_BAND:
        return float(AGE_MAX - AGE_TOP_THRESHOLD + 1)
    lower, upper = (int(part) for part in label.split("-"))
    return float(upper - lower + 1)


def _zip_specificity(label: str) -> float:
    """Coarseness of a ZIP output: fewer retained characters is coarser."""
    if label == SUPPRESSED:
        return float("inf")
    return float(-len(label))


def _date_specificity(label: str) -> float:
    """Coarseness of a date output by remaining granularity."""
    if label == SUPPRESSED:
        return 3.0
    granularity = label.count("-")  # day=2, month=1, year=0 dashes
    return float(2 - granularity)


def _clinical_code_specificity(label: str) -> float:
    """Coarseness for the exact-or-suppressed data-free code fallback."""
    return float("inf") if label == SUPPRESSED else 0.0


_SPECIFICITY = {
    COLUMN_TYPE_AGE: _age_specificity,
    COLUMN_TYPE_ZIP: _zip_specificity,
    COLUMN_TYPE_DATE: _date_specificity,
    COLUMN_TYPE_CLINICAL_CODE: _clinical_code_specificity,
}


def _generalize(column_type: str, value: object, level: int) -> str:
    kwargs = {}
    if column_type == COLUMN_TYPE_DATE:
        kwargs = {"patient_key": f"subject::{value}", "secret": SECRET}
    return generalize_value(column_type, value, level, **kwargs)


COLUMN_GRIDS = {
    COLUMN_TYPE_AGE: AGE_GRID,
    COLUMN_TYPE_ZIP: ZIP_GRID,
    COLUMN_TYPE_DATE: DATE_GRID,
    COLUMN_TYPE_CLINICAL_CODE: CLINICAL_CODE_GRID,
}


# --------------------------------------------------------------------------- #
# Contract / metadata                                                         #
# --------------------------------------------------------------------------- #
def test_supported_column_types_are_registered():
    assert SUPPORTED_COLUMN_TYPES == {
        COLUMN_TYPE_AGE,
        COLUMN_TYPE_CLINICAL_CODE,
        COLUMN_TYPE_ZIP,
        COLUMN_TYPE_DATE,
    }


@pytest.mark.parametrize("column_type", sorted(SUPPORTED_COLUMN_TYPES))
def test_hierarchy_exposes_ordered_versioned_levels(column_type):
    hierarchy = get_hierarchy(column_type)
    assert isinstance(hierarchy, Hierarchy)
    assert hierarchy.column_type == column_type
    assert hierarchy.version == HIERARCHY_SCHEMA_VERSION
    assert hierarchy.max_level == max_level(column_type)
    assert len(hierarchy.levels) == hierarchy.max_level + 1
    # Levels are index-aligned and describe_level round-trips.
    for index, level in enumerate(hierarchy.levels):
        assert isinstance(level, GeneralizationLevel)
        assert level.level == index
        assert describe_level(column_type, index) == level
        assert level.key and level.description
    # The coarsest rung is full suppression.
    assert (
        hierarchy.apply(
            next(iter(COLUMN_GRIDS[column_type])),
            hierarchy.max_level,
            patient_key="k",
            secret=SECRET,
        )
        == SUPPRESSED
    )
    # Machine keys are unique per hierarchy.
    keys = [level.key for level in hierarchy.levels]
    assert len(keys) == len(set(keys))


def test_hierarchy_apply_matches_module_function():
    d = "2021-06-15"
    hierarchy = get_hierarchy(COLUMN_TYPE_DATE)
    for level in range(hierarchy.max_level + 1):
        via_method = hierarchy.apply(d, level, patient_key="subject-A", secret=SECRET)
        via_function = generalize_value(
            COLUMN_TYPE_DATE, d, level, patient_key="subject-A", secret=SECRET
        )
        assert via_method == via_function


# --------------------------------------------------------------------------- #
# Acceptance: monotonicity over the whole grid                                #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("column_type", sorted(SUPPORTED_COLUMN_TYPES))
def test_monotone_non_increasing_specificity(column_type):
    """Level N+1 output is never more specific than level N (over a grid)."""
    specificity = _SPECIFICITY[column_type]
    top = max_level(column_type)
    for value in COLUMN_GRIDS[column_type]:
        previous = None
        for level in range(top + 1):
            output = _generalize(column_type, value, level)
            current = specificity(output)
            if previous is not None:
                assert current >= previous, (
                    f"{column_type} value {value!r} became more specific "
                    f"at level {level}: {output!r}"
                )
            previous = current


# --------------------------------------------------------------------------- #
# Acceptance: age bands                                                        #
# --------------------------------------------------------------------------- #
def test_age_top_band_collapses_to_single_band():
    for age in (AGE_TOP_THRESHOLD, AGE_TOP_THRESHOLD + 1, 120, AGE_MAX):
        for level in range(len(get_hierarchy(COLUMN_TYPE_AGE).levels) - 1):
            assert generalize_value(COLUMN_TYPE_AGE, age, level) == AGE_TOP_BAND


def test_age_boundary_bands_at_finest_level():
    assert generalize_value(COLUMN_TYPE_AGE, 0, 0) == "0-4"
    assert generalize_value(COLUMN_TYPE_AGE, 89, 0) == "85-89"
    assert generalize_value(COLUMN_TYPE_AGE, 90, 0) == AGE_TOP_BAND
    assert generalize_value(COLUMN_TYPE_AGE, 120, 0) == AGE_TOP_BAND


def test_no_age_band_below_minimum_width_on_grid():
    """Quantitative gate: zero sub-minimum bands across the fixture grid."""
    band_re = re.compile(r"^(\d+)-(\d+)$")
    offenders = []
    top = max_level(COLUMN_TYPE_AGE)
    for age in AGE_GRID:
        for level in range(top + 1):
            output = generalize_value(COLUMN_TYPE_AGE, age, level)
            match = band_re.match(output)
            if not match:
                continue
            lower, upper = int(match.group(1)), int(match.group(2))
            if (upper - lower + 1) < AGE_MIN_BAND_WIDTH:
                offenders.append((age, level, output))
    assert offenders == []


def test_age_bands_nest_across_levels():
    # 45 -> 45-49 (5y) within 40-49 (10y) within 40-59 (20y).
    assert generalize_value(COLUMN_TYPE_AGE, 45, 0) == "45-49"
    assert generalize_value(COLUMN_TYPE_AGE, 45, 1) == "40-49"
    assert generalize_value(COLUMN_TYPE_AGE, 45, 2) == "40-59"


def test_age_accepts_digit_strings():
    assert generalize_value(COLUMN_TYPE_AGE, "45", 0) == "45-49"


# --------------------------------------------------------------------------- #
# Acceptance: ZIP / postcode prefix truncation                                #
# --------------------------------------------------------------------------- #
def test_zip_prefix_truncation_drops_trailing_characters():
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 0) == "02139"
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 1) == "0213"
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 2) == "021"
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 3) == "02"
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 4) == "0"
    assert generalize_value(COLUMN_TYPE_ZIP, "02139", 5) == SUPPRESSED


def test_zip_seven_char_postcode_reaches_suppression():
    postcode = "SW1A1AA"
    assert generalize_value(COLUMN_TYPE_ZIP, postcode, 0) == postcode
    assert generalize_value(COLUMN_TYPE_ZIP, postcode, 1) == "SW1A1A"
    assert generalize_value(COLUMN_TYPE_ZIP, postcode, max_level(COLUMN_TYPE_ZIP)) == (
        SUPPRESSED
    )


def test_zip_all_grid_values_fully_suppress_at_top():
    top = max_level(COLUMN_TYPE_ZIP)
    for value in ZIP_GRID:
        assert generalize_value(COLUMN_TYPE_ZIP, value, top) == SUPPRESSED


# --------------------------------------------------------------------------- #
# Acceptance: date shift + truncation                                         #
# --------------------------------------------------------------------------- #
def test_date_shift_offset_is_stable_and_matches_core_helper():
    d = "2025-04-09"
    key = "patient-42"
    first = generalize_value(COLUMN_TYPE_DATE, d, 0, patient_key=key, secret=SECRET)
    second = generalize_value(COLUMN_TYPE_DATE, d, 0, patient_key=key, secret=SECRET)
    assert first == second
    offset = stable_offset_for(key, max_days=365, secret=SECRET)
    expected = (date(2025, 4, 9) + timedelta(days=offset)).isoformat()
    assert first == expected


def test_date_shift_preserves_interval_deltas():
    key = "patient-99"
    d1 = date(2025, 1, 1)
    d2 = date(2025, 3, 15)
    s1 = generalize_value(
        COLUMN_TYPE_DATE, d1.isoformat(), 0, patient_key=key, secret=SECRET
    )
    s2 = generalize_value(
        COLUMN_TYPE_DATE, d2.isoformat(), 0, patient_key=key, secret=SECRET
    )
    shifted1 = datetime.strptime(s1, "%Y-%m-%d").date()
    shifted2 = datetime.strptime(s2, "%Y-%m-%d").date()
    assert (shifted2 - shifted1) == (d2 - d1)


def test_date_truncation_drops_day_then_month():
    d = "2024-02-29"  # leap day
    assert generalize_value(COLUMN_TYPE_DATE, d, 1) == "2024-02"
    assert generalize_value(COLUMN_TYPE_DATE, d, 2) == "2024"
    assert (
        generalize_value(COLUMN_TYPE_DATE, d, max_level(COLUMN_TYPE_DATE)) == SUPPRESSED
    )


def test_date_shift_requires_patient_key_and_secret():
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_DATE, "2025-01-01", 0)
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_DATE, "2025-01-01", 0, patient_key="k")


@pytest.mark.parametrize(
    "kwargs",
    [
        {"patient_key": "", "secret": SECRET},
        {"patient_key": "patient-1", "secret": ""},
        {"patient_key": "patient-1", "secret": SECRET, "max_days": 0},
    ],
)
def test_invalid_date_shift_parameters_raise_typed_error(kwargs):
    with pytest.raises(HierarchyError, match="parameters are invalid"):
        generalize_value(COLUMN_TYPE_DATE, "2025-01-01", 0, **kwargs)


def test_date_shift_range_overflow_raises_typed_error():
    patient_key = "boundary-patient"
    max_days = 1
    offset = stable_offset_for(patient_key, max_days=max_days, secret=SECRET)
    boundary = date.min if offset < 0 else date.max

    with pytest.raises(HierarchyError, match="exceeds the supported date range"):
        generalize_value(
            COLUMN_TYPE_DATE,
            boundary,
            0,
            patient_key=patient_key,
            secret=SECRET,
            max_days=max_days,
        )


def test_date_shift_preserves_canonical_iso_format_at_year_boundary():
    patient_key = "k"
    max_days = 1
    offset = stable_offset_for(patient_key, max_days=max_days, secret=SECRET)
    assert offset > 0

    shifted = generalize_value(
        COLUMN_TYPE_DATE,
        date.min,
        0,
        patient_key=patient_key,
        secret=SECRET,
        max_days=max_days,
    )

    assert shifted == (date.min + timedelta(days=offset)).isoformat()
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", shifted)


@pytest.mark.parametrize(
    "value",
    [
        "2024-2-9",
        "2024-02-9",
        "20240209",
        " 2024-02-09 ",
        "\t2024-02-09",
        "2024-02-09\n",
    ],
)
def test_date_requires_canonical_iso_string(value):
    with pytest.raises(HierarchyError, match="ISO YYYY-MM-DD"):
        generalize_value(COLUMN_TYPE_DATE, value, 1)


# --------------------------------------------------------------------------- #
# Acceptance: typed errors and validation                                     #
# --------------------------------------------------------------------------- #
def test_unknown_column_type_raises_typed_error():
    with pytest.raises(HierarchyError):
        generalize_value("weight", 42, 0)
    with pytest.raises(HierarchyError):
        get_hierarchy("weight")
    with pytest.raises(HierarchyError):
        max_level(None)


@pytest.mark.parametrize("column_type", sorted(SUPPORTED_COLUMN_TYPES))
def test_out_of_range_level_raises_typed_error(column_type):
    top = max_level(column_type)
    value = next(iter(COLUMN_GRIDS[column_type]))
    with pytest.raises(HierarchyError):
        _generalize(column_type, value, -1)
    with pytest.raises(HierarchyError):
        _generalize(column_type, value, top + 1)
    with pytest.raises(HierarchyError):
        describe_level(column_type, True)  # bool rejected as a level


def test_invalid_values_raise_typed_error():
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_AGE, -1, 0)
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_AGE, AGE_MAX + 1, 0)
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_AGE, "not-a-number", 0)
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_ZIP, "02-13", 0)
    with pytest.raises(HierarchyError):
        generalize_value(COLUMN_TYPE_ZIP, "", 0)
    with pytest.raises(HierarchyError):
        generalize_value(
            COLUMN_TYPE_DATE, "2025-13-40", 0, patient_key="k", secret=SECRET
        )


# --------------------------------------------------------------------------- #
# Integration: the declarative family plugs into enforce_kanon                #
# --------------------------------------------------------------------------- #
def test_to_enforce_kanon_hierarchy_shape():
    # Age enumerates its bounded domain without observed values; the spec is
    # identity-first and each coarsening rung carries a value map (or default).
    spec = to_enforce_kanon_hierarchy(COLUMN_TYPE_AGE)
    assert spec[0] == {"name": "age:exact"}
    assert "values" not in spec[0] and "default" not in spec[0]
    assert spec[1]["values"]["45"] == "45-49"  # 5-year band rung
    assert spec[-1] == {"name": "age:suppressed", "default": SUPPRESSED}

    # The per-subject date shift rung is NOT emitted (not a class merge); the
    # emitted date spec is identity -> month -> year -> suppressed.
    date_spec = to_enforce_kanon_hierarchy(
        COLUMN_TYPE_DATE, ["2024-02-29", "2024-02-15"]
    )
    assert [level["name"] for level in date_spec] == [
        "date:exact",
        "date:month",
        "date:year",
        "date:suppressed",
    ]
    assert date_spec[1]["values"]["2024-02-29"] == "2024-02"

    # ZIP and date require observed values (unbounded domains).
    with pytest.raises(HierarchyError):
        to_enforce_kanon_hierarchy(COLUMN_TYPE_ZIP)
    with pytest.raises(HierarchyError):
        to_enforce_kanon_hierarchy(COLUMN_TYPE_DATE)
    with pytest.raises(HierarchyError):
        to_enforce_kanon_hierarchy(COLUMN_TYPE_CLINICAL_CODE, ["A1"])


def test_clinical_code_hierarchy_is_materialized_from_pure_parent_chain_data():
    parent_chains = {
        "A1": ("A", "ROOT"),
        "A2": ("A", "ROOT"),
        "B1": ("B", "ROOT"),
    }
    spec = to_enforce_kanon_hierarchy(
        COLUMN_TYPE_CLINICAL_CODE,
        list(parent_chains),
        clinical_code_parent_chains=parent_chains,
    )

    assert [level["name"] for level in spec] == [
        "clinical_code:exact",
        "clinical_code:parent_1",
        "clinical_code:parent_2",
        "clinical_code:suppressed",
    ]
    assert spec[1]["values"]["A1"] == "A"
    assert spec[2]["values"]["A1"] == "ROOT"
    assert spec[-1] == {
        "name": "clinical_code:suppressed",
        "default": SUPPRESSED,
    }


def test_clinical_code_parent_data_cannot_split_an_earlier_merge():
    with pytest.raises(HierarchyError, match="split a class"):
        to_enforce_kanon_hierarchy(
            COLUMN_TYPE_CLINICAL_CODE,
            ["A1", "A2"],
            clinical_code_parent_chains={
                "A1": ("A", "ROOT-1"),
                "A2": ("A", "ROOT-2"),
            },
        )


def _synthetic_kanon_table():
    """Eight synthetic records forming four pairs that merge at coarse rungs."""
    records = []
    for i in range(8):
        pair = i // 2
        records.append(
            {
                "pid": f"p{i}",
                "age": 20 + pair * 10 + (i % 2),
                "zip": f"{10000 + pair * 100 + (i % 2):05d}",
                "admit_date": f"2025-{pair + 1:02d}-{(i % 2) + 1:02d}",
            }
        )
    return records


def test_declarative_family_plugs_into_enforce_kanon():
    records = _synthetic_kanon_table()
    column_to_type = {
        "age": COLUMN_TYPE_AGE,
        "zip": COLUMN_TYPE_ZIP,
        "admit_date": COLUMN_TYPE_DATE,
    }
    hierarchies = build_enforcement_hierarchies(column_to_type, records)
    assert set(hierarchies) == set(column_to_type)

    target_k = 2
    enforced = enforce_kanon(
        records,
        quasi_identifiers=["age", "zip", "admit_date"],
        hierarchies=hierarchies,
        target_k=target_k,
        remove_direct_identifiers=False,
    )

    # The engine accepted the declarative levels and reached the target k by
    # generalization alone (no suppression), proving the rungs are usable.
    assert enforced["kanon"]["k"] >= target_k
    assert enforced["suppressed_count"] == 0
    assert enforced["released_count"] == len(records)


def test_build_enforcement_hierarchies_rejects_unknown_type():
    with pytest.raises(HierarchyError):
        build_enforcement_hierarchies({"weight": "weight"}, [{"weight": 70}])


def test_module_imports_without_jvm_or_terminology():
    import importlib
    import sys

    for blocked in ("jpype", "py4j", "pyspark"):
        assert blocked not in sys.modules
    module = importlib.import_module("openmed.structured.hierarchies.functions")
    assert module.SUPPORTED_COLUMN_TYPES == SUPPORTED_COLUMN_TYPES
