"""Custom Faker providers for clinical / national IDs that Faker doesn't
cover natively or covers with the wrong format.

These providers integrate with Faker's standard ``add_provider`` mechanism
and produce values that pass the existing checksum validators in
:mod:`openmed.core.pii_i18n`.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from .clinical_ids import (
    KENYA_MFL_SYNTHETIC_MAX,
    KENYA_MFL_SYNTHETIC_MIN,
    NIGERIA_HFR_SYNTHETIC_SERIAL_MAX,
    NIGERIA_HFR_SYNTHETIC_SERIAL_MIN,
    AadhaarProvider,
    ABDMProvider,
    AfricanPhoneProvider,
    BelgianRRNProvider,
    BulgarianEgnProvider,
    ChineseIdentifierProvider,
    ChineseNameProvider,
    DanishCPRProvider,
    EastAfricanIdProvider,
    EstonianIsikukoodProvider,
    FinancialIdentifierProvider,
    GermanSteuerIdProvider,
    HealthFacilityCodeProvider,
    HungarianTAJProvider,
    IndiaHealthIdProvider,
    IndianIdentifierProvider,
    IndiaSurrogateProvider,
    IndonesianNIKProvider,
    IsraeliTeudatZehutProvider,
    KoreanRRNProvider,
    LatvianPersonasKodsProvider,
    MedicalRecordNumberProvider,
    MobileMoneyProvider,
    MpesaProvider,
    NPIProvider,
    PhilippinesIdProvider,
    PolishPeselProvider,
    PortugueseNIFProvider,
    RomanianCNPProvider,
    SerbianJmbgProvider,
    SpanishDNIProvider,
    SwissAHVProvider,
    UkrainianRnokppProvider,
    VietnameseIdProvider,
    generate_abha,
    generate_abha_address,
    generate_abha_number,
    generate_african_phone,
    generate_belgian_rrn,
    generate_bic,
    generate_bulgarian_egn,
    generate_chinese_bank_card,
    generate_chinese_given_name,
    generate_chinese_mobile_number,
    generate_chinese_name,
    generate_chinese_passport,
    generate_chinese_surname,
    generate_danish_cpr,
    generate_estonian_isikukood,
    generate_ethiopia_fayda,
    generate_gstin,
    generate_hong_kong_macau_permit,
    generate_hungarian_taj,
    generate_iban,
    generate_ifsc,
    generate_indian_driving_licence,
    generate_indian_passport,
    generate_indian_phone,
    generate_indian_pin,
    generate_indian_ration_card,
    generate_indonesian_nik,
    generate_jmbg,
    generate_korean_rrn,
    generate_latvian_personas_kods,
    generate_mpesa_transaction_code,
    generate_pan,
    generate_pesel,
    generate_philhealth_pin,
    generate_philsys_psn,
    generate_portuguese_nif,
    generate_romanian_cnp,
    generate_rwanda_id,
    generate_swiss_ahv,
    generate_taiwan_compatriot_permit,
    generate_tanzania_nida,
    generate_teudat_zehut,
    generate_uganda_nin,
    generate_ukrainian_rnokpp,
    generate_upi_id,
    generate_vehicle_registration,
    generate_vietnamese_cccd,
    generate_vietnamese_cmnd,
    generate_voter_id_epic,
    register_clinical_providers,
    validate_abdm_registry_id,
    validate_abha,
    validate_abha_address,
    validate_abha_number,
    validate_gstin,
    validate_indian_phone,
    validate_indian_pin,
    validate_mrn,
    validate_pan,
)
from .script_names import (
    DEVANAGARI_LANGUAGE_PACK,
    HAN_LANGUAGE_PACK,
    SCRIPT_NAME_PACKS,
    TELUGU_LANGUAGE_PACK,
    generate_devanagari_name,
    generate_han_name,
    generate_telugu_name,
)

if TYPE_CHECKING:
    from .registry_ids import (
        AUXILIARY_FAKER_PROVIDER_CLASSES,
        ID_PROVIDER_REGISTRY,
        NationalIdSpec,
        clinical_faker_provider_classes,
        get_national_id,
        register_national_id,
    )

_LAZY_IMPORTS = {
    "AUXILIARY_FAKER_PROVIDER_CLASSES": ".registry_ids",
    "ID_PROVIDER_REGISTRY": ".registry_ids",
    "NationalIdSpec": ".registry_ids",
    "clinical_faker_provider_classes": ".registry_ids",
    "get_national_id": ".registry_ids",
    "register_national_id": ".registry_ids",
}


def __getattr__(name: str) -> Any:
    """Resolve registry-backed provider exports without creating an import cycle."""

    module_name = _LAZY_IMPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return eager and lazy provider exports for interactive discovery."""

    return sorted(set(globals()) | set(_LAZY_IMPORTS))


__all__ = [
    "ABDMProvider",
    "AadhaarProvider",
    "BelgianRRNProvider",
    "AfricanPhoneProvider",
    "AUXILIARY_FAKER_PROVIDER_CLASSES",
    "BulgarianEgnProvider",
    "ChineseIdentifierProvider",
    "ChineseNameProvider",
    "DanishCPRProvider",
    "DEVANAGARI_LANGUAGE_PACK",
    "EastAfricanIdProvider",
    "EstonianIsikukoodProvider",
    "FinancialIdentifierProvider",
    "GermanSteuerIdProvider",
    "HealthFacilityCodeProvider",
    "HungarianTAJProvider",
    "IndiaHealthIdProvider",
    "IndianIdentifierProvider",
    "IndiaSurrogateProvider",
    "HAN_LANGUAGE_PACK",
    "ID_PROVIDER_REGISTRY",
    "IndonesianNIKProvider",
    "IsraeliTeudatZehutProvider",
    "KoreanRRNProvider",
    "KENYA_MFL_SYNTHETIC_MAX",
    "KENYA_MFL_SYNTHETIC_MIN",
    "LatvianPersonasKodsProvider",
    "MedicalRecordNumberProvider",
    "MobileMoneyProvider",
    "MpesaProvider",
    "NPIProvider",
    "NIGERIA_HFR_SYNTHETIC_SERIAL_MAX",
    "NIGERIA_HFR_SYNTHETIC_SERIAL_MIN",
    "NationalIdSpec",
    "PhilippinesIdProvider",
    "PolishPeselProvider",
    "PortugueseNIFProvider",
    "RomanianCNPProvider",
    "SerbianJmbgProvider",
    "SCRIPT_NAME_PACKS",
    "SpanishDNIProvider",
    "SwissAHVProvider",
    "TELUGU_LANGUAGE_PACK",
    "UkrainianRnokppProvider",
    "VietnameseIdProvider",
    "clinical_faker_provider_classes",
    "generate_abha",
    "generate_bic",
    "generate_belgian_rrn",
    "generate_abha_address",
    "generate_abha_number",
    "generate_african_phone",
    "generate_bulgarian_egn",
    "generate_chinese_bank_card",
    "generate_chinese_given_name",
    "generate_chinese_mobile_number",
    "generate_chinese_name",
    "generate_chinese_passport",
    "generate_chinese_surname",
    "generate_danish_cpr",
    "generate_devanagari_name",
    "generate_hungarian_taj",
    "generate_gstin",
    "generate_ifsc",
    "generate_hong_kong_macau_permit",
    "generate_han_name",
    "generate_estonian_isikukood",
    "generate_ethiopia_fayda",
    "generate_iban",
    "generate_indian_phone",
    "generate_indian_pin",
    "generate_indian_driving_licence",
    "generate_indian_passport",
    "generate_indonesian_nik",
    "generate_indian_ration_card",
    "generate_jmbg",
    "generate_tanzania_nida",
    "generate_teudat_zehut",
    "generate_taiwan_compatriot_permit",
    "generate_telugu_name",
    "generate_uganda_nin",
    "generate_upi_id",
    "generate_vehicle_registration",
    "generate_ukrainian_rnokpp",
    "generate_vietnamese_cccd",
    "generate_vietnamese_cmnd",
    "generate_voter_id_epic",
    "generate_korean_rrn",
    "generate_latvian_personas_kods",
    "generate_mpesa_transaction_code",
    "generate_philhealth_pin",
    "generate_philsys_psn",
    "generate_pan",
    "generate_pesel",
    "generate_portuguese_nif",
    "generate_rwanda_id",
    "generate_romanian_cnp",
    "generate_swiss_ahv",
    "get_national_id",
    "register_clinical_providers",
    "register_national_id",
    "validate_abdm_registry_id",
    "validate_abha_address",
    "validate_abha_number",
    "validate_abha",
    "validate_gstin",
    "validate_indian_phone",
    "validate_indian_pin",
    "validate_mrn",
    "validate_pan",
]
