"""Local-first helpers for privacy-safe agent traces."""

from .discovery import (
    SUPPORTED_TRACE_ROOT_RULES,
    TRACE_DISCOVERY_ENV_VAR,
    TRACE_ROOTS_ENV_VAR,
    TraceRootRule,
    TraceStore,
    TraceStoreSummary,
    discover_trace_stores,
)
from .schemas.preference import (
    CONTENT_FIELDS,
    PREFERENCE_SCHEMA_VERSION,
    PreferencePair,
    PreferencePairAdapter,
    PreferenceRedactionError,
    PreferenceRedactionReport,
    PreferenceRedactionResult,
    PreferenceRedactionState,
    PreferenceSchemaError,
    PreferenceSpan,
    SensitiveSpan,
    adapt_preference_pair,
    redact_preference_dataset,
    redact_preference_pair,
)

__all__ = [
    "CONTENT_FIELDS",
    "PREFERENCE_SCHEMA_VERSION",
    "SUPPORTED_TRACE_ROOT_RULES",
    "TRACE_DISCOVERY_ENV_VAR",
    "TRACE_ROOTS_ENV_VAR",
    "PreferencePair",
    "PreferencePairAdapter",
    "PreferenceRedactionError",
    "PreferenceRedactionReport",
    "PreferenceRedactionResult",
    "PreferenceRedactionState",
    "PreferenceSchemaError",
    "PreferenceSpan",
    "SensitiveSpan",
    "TraceRootRule",
    "TraceStore",
    "TraceStoreSummary",
    "adapt_preference_pair",
    "discover_trace_stores",
    "redact_preference_dataset",
    "redact_preference_pair",
]
