"""Re-identification risk package for section 4.2."""

from .audit_diff import AuditDiff, diff_audit_reports
from .budget import (
    DEFAULT_DP_SURROGATE_SENSITIVITIES,
    DEFAULT_POLICY_BUDGETS,
    DEFAULT_QI_WEIGHTS,
    DEFAULT_RDP_ORDERS,
    DEFAULT_RISK_BUDGET,
    DPSurrogateBudget,
    DPSurrogateBudgetExceeded,
    DPSurrogateComposition,
    DPSurrogateSensitivity,
    DPSurrogateSensitivityRegistry,
    DPSurrogateSpend,
    RiskBudget,
    RiskBudgetExceeded,
    RiskBudgetVerdict,
    RiskBudgetViolation,
    SurrogateDrawKind,
    budget_for_policy,
    evaluate_budget,
)
from .dashboard import render_risk_dashboard, write_risk_dashboard
from .k_anonymity import (
    EquivalenceClass,
    KAnonymityEngine,
    KAnonymityReport,
    SuppressionProposal,
    analyze_k_anonymity,
    apply_suppression,
    propose_suppression,
)
from .kanon import build_generalization_hierarchies, enforce_kanon, kanon_report
from .reid import (
    LongitudinalCorpus,
    LongitudinalEvidence,
    LongitudinalNote,
    LongitudinalPatient,
    build_longitudinal_corpus,
    longitudinal_attack_fingerprint,
    longitudinal_risk_report,
    risk_report,
)
from .synthetic_tabular import (
    DEFAULT_CORRELATION_TOLERANCE,
    DEFAULT_MARGINAL_TOLERANCE,
    ColumnDistribution,
    TabularProfile,
    fit_tabular_profile,
    sample_synthetic_table,
    tabular_fidelity_report,
)

__all__ = [
    "DEFAULT_DP_SURROGATE_SENSITIVITIES",
    "DEFAULT_CORRELATION_TOLERANCE",
    "DEFAULT_MARGINAL_TOLERANCE",
    "DEFAULT_POLICY_BUDGETS",
    "DEFAULT_QI_WEIGHTS",
    "DEFAULT_RDP_ORDERS",
    "DEFAULT_RISK_BUDGET",
    "DPSurrogateBudget",
    "DPSurrogateBudgetExceeded",
    "DPSurrogateComposition",
    "DPSurrogateSensitivity",
    "DPSurrogateSensitivityRegistry",
    "DPSurrogateSpend",
    "ColumnDistribution",
    "EquivalenceClass",
    "KAnonymityEngine",
    "KAnonymityReport",
    "RiskBudget",
    "RiskBudgetExceeded",
    "RiskBudgetVerdict",
    "RiskBudgetViolation",
    "LongitudinalCorpus",
    "LongitudinalEvidence",
    "LongitudinalNote",
    "LongitudinalPatient",
    "SurrogateDrawKind",
    "SuppressionProposal",
    "TabularProfile",
    "analyze_k_anonymity",
    "apply_suppression",
    "budget_for_policy",
    "build_longitudinal_corpus",
    "evaluate_budget",
    "fit_tabular_profile",
    "longitudinal_attack_fingerprint",
    "longitudinal_risk_report",
    "risk_report",
    "sample_synthetic_table",
    "tabular_fidelity_report",
    "build_generalization_hierarchies",
    "enforce_kanon",
    "kanon_report",
    "propose_suppression",
    "diff_audit_reports",
    "AuditDiff",
    "render_risk_dashboard",
    "write_risk_dashboard",
]
