#!/usr/bin/env python3
"""Build deterministic website and documentation token consumers."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TOKEN_DIR = REPO_ROOT / "docs/brand/system/tokens"
FONT_DIR = REPO_ROOT / "docs/brand/assets/fonts"
TOKEN_FILES = ("colors.css", "typography.css", "surfaces.css")
CONSUMERS = {
    REPO_ROOT / "docs/website/assets/openmed-system.css": {
        "name": "website",
        "font_prefix": "fonts/",
        "editorial": True,
    },
    REPO_ROOT / "docs/stylesheets/openmed-system.css": {
        "name": "docs",
        "font_prefix": "../assets/fonts/",
        "editorial": False,
    },
}
FONT_DESTINATIONS = {
    "docs": REPO_ROOT / "docs/assets/fonts",
    "website": REPO_ROOT / "docs/website/assets/fonts",
}
IDENTITY_COPIES = {
    REPO_ROOT / "docs/brand/assets/open-cross.svg": (
        REPO_ROOT / "docs/assets/openmed-mark.svg",
        REPO_ROOT / "docs/assets/openmed-favicon.svg",
        REPO_ROOT / "docs/website/logo.svg",
        REPO_ROOT / "docs/website/favicon.svg",
    ),
    REPO_ROOT / "docs/brand/assets/open-cross-inverse.svg": (
        REPO_ROOT / "docs/assets/openmed-mark-inverse.svg",
        REPO_ROOT / "docs/website/logo-inverse.svg",
    ),
}
EDITORIAL_START = "/* openmed-editorial-exception:start */"
EDITORIAL_END = "/* openmed-editorial-exception:end */"


def build_consumer(font_prefix: str, *, editorial: bool) -> str:
    """Return the canonical token bundle with consumer-relative font URLs."""

    header = (
        "/* GENERATED by scripts/brand/sync_consumers.py.\n"
        "   Source: docs/brand/system/tokens/*.css. Do not edit directly. */\n\n"
    )
    sections = []
    for filename in TOKEN_FILES:
        source = (TOKEN_DIR / filename).read_text(encoding="utf-8").rstrip()
        if filename == "typography.css" and not editorial:
            before, marker, remainder = source.partition(EDITORIAL_START)
            if not marker:
                raise RuntimeError("typography.css has no editorial start marker")
            _exception, marker, after = remainder.partition(EDITORIAL_END)
            if not marker:
                raise RuntimeError("typography.css has no editorial end marker")
            source = before.rstrip() + "\n\n" + after.lstrip()
        source = source.replace("../../assets/fonts/", font_prefix)
        sections.append(f"/* source: {filename} */\n{source}")
    return header + "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    font_manifest = json.loads((FONT_DIR / "manifest.json").read_text(encoding="utf-8"))
    for output, config in CONSUMERS.items():
        expected = build_consumer(
            config["font_prefix"],
            editorial=config["editorial"],
        )
        if args.write:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8")
            print(f"wrote {output.relative_to(REPO_ROOT)}")
            continue
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            stale.append(str(output.relative_to(REPO_ROOT)))

    published_bytes = 0
    published_by_consumer: dict[str, int] = {}
    for consumer, destination_dir in FONT_DESTINATIONS.items():
        web_files = [
            item["web_file"]
            for item in font_manifest["files"]
            if consumer in item["consumers"]
        ]
        consumer_bytes = 0
        for filename in web_files:
            source = FONT_DIR / filename
            destination = destination_dir / filename
            consumer_bytes += source.stat().st_size
            if args.write:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, destination)
                print(f"wrote {destination.relative_to(REPO_ROOT)}")
                continue
            if (
                not destination.exists()
                or destination.read_bytes() != source.read_bytes()
            ):
                stale.append(str(destination.relative_to(REPO_ROOT)))
        published_by_consumer[consumer] = consumer_bytes
        published_bytes += consumer_bytes

        unexpected = (
            set(destination_dir.glob("*.ttf")) | set(destination_dir.glob("*.woff2"))
        ) - {destination_dir / filename for filename in web_files}
        if unexpected:
            stale.extend(
                str(path.relative_to(REPO_ROOT)) for path in sorted(unexpected)
            )

    budgets = font_manifest["budgets"]
    if published_by_consumer["docs"] > budgets["docs_woff2_bytes_max"]:
        stale.append("docs font payload exceeds its recorded budget")
    if published_by_consumer["website"] > budgets["website_woff2_bytes_max"]:
        stale.append("website font payload exceeds its recorded budget")
    if published_bytes > budgets["combined_published_woff2_bytes_max"]:
        stale.append("combined font payload exceeds its recorded budget")

    for source, destinations in IDENTITY_COPIES.items():
        for destination in destinations:
            if args.write:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, destination)
                print(f"wrote {destination.relative_to(REPO_ROOT)}")
            elif (
                not destination.exists()
                or destination.read_bytes() != source.read_bytes()
            ):
                stale.append(str(destination.relative_to(REPO_ROOT)))

    if stale:
        print(
            "stale design-system consumers: "
            + ", ".join(stale)
            + "; run python scripts/brand/sync_consumers.py --write",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("design-system consumers are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
