"""Redaction-preserving retrieval primitives."""

from .redacted_index import (
    INDEX_SCHEMA_VERSION,
    IndexingResult,
    PlaceholderOffset,
    RedactedChunk,
    RedactedIndex,
)
from .reidentify import (
    DOCUMENT_KEY_SCHEME,
    PLACEHOLDER_PATTERN,
    VAULT_ENCRYPTION_SCHEME,
    VAULT_SCHEMA_VERSION,
    AuthorizedReidentifier,
    EncryptedMappingVault,
    GatewayProxy,
    InvalidDocumentKeyError,
    MappingVaultIntegrityError,
    PrivacyGatewayProxyError,
    ReidentificationAuditRecord,
    ReidentificationAuditTrail,
    ReidentificationError,
    UnauthorizedPrincipalError,
    UnknownDocumentError,
    UnknownPlaceholderError,
)
from .retriever import (
    ExternalLLMGatewayProxy,
    GatewayBoundExternalLLM,
    InMemoryVectorStore,
    RedactedLLMResponse,
    RedactedRetriever,
    RetrievedPassage,
)

__all__ = [
    "AuthorizedReidentifier",
    "DOCUMENT_KEY_SCHEME",
    "EncryptedMappingVault",
    "ExternalLLMGatewayProxy",
    "GatewayBoundExternalLLM",
    "GatewayProxy",
    "INDEX_SCHEMA_VERSION",
    "InMemoryVectorStore",
    "InvalidDocumentKeyError",
    "IndexingResult",
    "MappingVaultIntegrityError",
    "PLACEHOLDER_PATTERN",
    "PlaceholderOffset",
    "PrivacyGatewayProxyError",
    "RedactedChunk",
    "RedactedIndex",
    "RedactedLLMResponse",
    "RedactedRetriever",
    "ReidentificationAuditRecord",
    "ReidentificationAuditTrail",
    "ReidentificationError",
    "RetrievedPassage",
    "UnauthorizedPrincipalError",
    "UnknownDocumentError",
    "UnknownPlaceholderError",
    "VAULT_ENCRYPTION_SCHEME",
    "VAULT_SCHEMA_VERSION",
]
