"""Focused tests for the post-de-identification summary safety envelope."""

from __future__ import annotations

from types import SimpleNamespace
from typing import Literal, get_type_hints

import pytest

from openmed.clinical.summary_envelope import (
    SUMMARY_REFUSAL_GENERATION,
    SUMMARY_REFUSAL_HUMAN_REVIEW,
    SUMMARY_REFUSAL_INVALID_ARTIFACT,
    SUMMARY_REFUSAL_MISSING_ARTIFACT,
    SUMMARY_SAFETY_DISCLAIMER,
    SummaryEnvelope,
    SummaryEnvelopeError,
    VerifiedDeidentifiedArtifact,
    build_summary_envelope,
    run_summary_stage,
    validate_summary_envelope,
    verify_deidentified_artifact,
)


def _synthetic_result() -> SimpleNamespace:
    return SimpleNamespace(
        original_text="ORIGINAL_ONLY_MARKER",
        deidentified_text="Clinical note [NAME] has [LAB_VALUE].",
        pii_entities=[{"text": "ORIGINAL_ONLY_MARKER", "label": "NAME"}],
        method="mask",
        metadata={"pipeline": "synthetic-local"},
    )


def test_verification_factory_discards_original_content_and_keeps_hash_traceability():
    artifact = verify_deidentified_artifact(
        _synthetic_result(),
        artifact_id="synthetic-note-001",
        provenance={"policy": "offline-synthetic"},
    )

    assert isinstance(artifact, VerifiedDeidentifiedArtifact)
    assert artifact.payload == "Clinical note [NAME] has [LAB_VALUE]."
    assert artifact.verified is True
    assert artifact.is_verified is True
    assert artifact.to_dict()["artifact_id"] == "synthetic-note-001"
    assert artifact.to_dict()["content_hash"].startswith("sha256:")
    assert "ORIGINAL_ONLY_MARKER" not in repr(artifact)
    assert "ORIGINAL_ONLY_MARKER" not in str(artifact.to_dict())


def test_audit_hash_is_verified_without_copying_audit_content():
    result = _synthetic_result()
    audit = SimpleNamespace(
        input_hash="sha256:" + "1" * 64,
        deidentified_text_hash=(
            "sha256:f0a4a5b3f4d7a8c6b7d8e9f0a1b2c3d4e5f60718293a4b5c6d7e8f9012345678"
        ),
        repro_hash_matches=lambda: True,
    )
    result.audit_report = audit

    # The expected hash is generated by the artifact factory, so use a matching
    # report value for the verification path.
    import hashlib

    result.audit_report.deidentified_text_hash = (
        "sha256:" + hashlib.sha256(result.deidentified_text.encode()).hexdigest()
    )
    artifact = verify_deidentified_artifact(result)

    assert artifact.source_hash == "sha256:" + "1" * 64
    assert artifact.verification_method == "deidentification_result"
    assert "input_hash" not in artifact.to_dict()


def test_raw_text_cannot_be_used_as_a_verified_input():
    with pytest.raises(SummaryEnvelopeError, match="not verifiable"):
        verify_deidentified_artifact("ORIGINAL_ONLY_MARKER")


def test_raw_metadata_and_reserved_traceability_fields_are_rejected():
    result = _synthetic_result()
    result.metadata = {"original_text": "ORIGINAL_ONLY_MARKER"}
    with pytest.raises(SummaryEnvelopeError, match="source content"):
        verify_deidentified_artifact(result)

    artifact = verify_deidentified_artifact(_synthetic_result())
    with pytest.raises(SummaryEnvelopeError, match="reserved metadata"):
        build_summary_envelope(
            {"section_count": 1},
            artifact=artifact,
            human_review_mode=True,
            provenance={"verified": False},
        )


def test_direct_artifact_construction_is_not_a_supported_bypass():
    with pytest.raises(SummaryEnvelopeError, match="use verify_deidentified_artifact"):
        VerifiedDeidentifiedArtifact(
            payload="Clinical note [NAME]",
            artifact_id="synthetic-note-001",
            source_hash="sha256:" + "1" * 64,
            content_hash="sha256:" + "2" * 64,
            deidentification_method="mask",
            verification_method="test",
        )


def test_summary_producer_is_not_called_without_verified_artifact():
    calls: list[str] = []

    def producer(_: str) -> dict[str, int]:
        calls.append("called")
        return {"section_count": 1}

    refused = run_summary_stage(
        "not-an-artifact",
        producer,
        human_review_mode=True,
    )

    assert refused.status == "refused"
    assert refused.summary is None
    assert refused.refusal_reasons == (SUMMARY_REFUSAL_INVALID_ARTIFACT,)
    assert calls == []


def test_summary_producer_is_not_called_without_explicit_human_review_mode():
    artifact = verify_deidentified_artifact(_synthetic_result())
    calls: list[str] = []

    def producer(_: str) -> dict[str, int]:
        calls.append("called")
        return {"section_count": 1}

    refused = run_summary_stage(artifact, producer)

    assert refused.status == "refused"
    assert refused.refusal_reasons == (SUMMARY_REFUSAL_HUMAN_REVIEW,)
    assert calls == []
    assert refused.disclaimer == SUMMARY_SAFETY_DISCLAIMER
    assert refused.requires_human_review is True
    assert refused.is_diagnostic is False


def test_ready_envelope_contains_only_safe_provenance_and_mandatory_disclaimer():
    artifact = verify_deidentified_artifact(
        _synthetic_result(),
        artifact_id="synthetic-note-001",
    )
    result = run_summary_stage(
        artifact,
        lambda text: {"entity_counts": {"problems": 1}, "input_length": len(text)},
        human_review_mode=True,
        provenance={"producer": "local-summary-v1"},
    )

    assert result.status == "ready"
    assert result.summary == {"entity_counts": {"problems": 1}, "input_length": 37}
    assert result.provenance["artifact_id"] == "synthetic-note-001"
    assert result.provenance["deidentification_method"] == "mask"
    assert result.provenance["producer"] == "local-summary-v1"
    assert result.refusal_reasons == ()
    assert result.disclaimer == SUMMARY_SAFETY_DISCLAIMER
    assert result.human_review_required is True
    assert result.is_diagnostic is False
    serialized = result.to_json()
    assert "ORIGINAL_ONLY_MARKER" not in serialized
    assert "pii_entities" not in serialized


def test_summary_serialization_is_deterministic_and_round_trips():
    artifact = verify_deidentified_artifact(_synthetic_result())
    first = build_summary_envelope(
        {"z": 2, "a": {"b": 1}},
        artifact=artifact,
        human_review_mode=True,
    )
    second = build_summary_envelope(
        {"a": {"b": 1}, "z": 2},
        artifact=artifact,
        human_review_mode=True,
    )

    assert first.to_json() == second.to_json()
    restored = validate_summary_envelope(first.to_dict())
    assert restored.to_dict() == first.to_dict()


def test_invalid_build_discards_precomputed_summary_and_reports_all_missing_gates():
    refused = build_summary_envelope(
        {"section_count": 1},
        human_review_mode=False,
    )

    assert refused.status == "refused"
    assert refused.summary is None
    assert refused.refusal_reasons == (
        SUMMARY_REFUSAL_MISSING_ARTIFACT,
        SUMMARY_REFUSAL_HUMAN_REVIEW,
    )


def test_producer_failure_is_a_privacy_safe_refusal():
    artifact = verify_deidentified_artifact(_synthetic_result())

    def producer(_: str) -> str:
        raise RuntimeError("producer saw ORIGINAL_ONLY_MARKER")

    refused = run_summary_stage(artifact, producer, human_review_mode=True)

    assert refused.status == "refused"
    assert refused.refusal_reasons == (SUMMARY_REFUSAL_GENERATION,)
    assert "ORIGINAL_ONLY_MARKER" not in refused.to_json()


def test_tampered_disclaimer_and_review_flags_are_rejected():
    artifact = verify_deidentified_artifact(_synthetic_result())
    payload = build_summary_envelope(
        {"section_count": 1},
        artifact=artifact,
        human_review_mode=True,
    ).to_dict()
    payload["disclaimer"] = ""
    with pytest.raises(SummaryEnvelopeError):
        validate_summary_envelope(payload)

    payload = build_summary_envelope(
        {"section_count": 1},
        artifact=artifact,
        human_review_mode=True,
    ).to_dict()
    payload["provenance"]["text"] = "ORIGINAL_ONLY_MARKER"
    with pytest.raises(SummaryEnvelopeError):
        validate_summary_envelope(payload)

    payload = build_summary_envelope(
        {"section_count": 1},
        artifact=artifact,
        human_review_mode=True,
    ).to_dict()
    payload["is_diagnostic"] = True
    with pytest.raises(SummaryEnvelopeError):
        validate_summary_envelope(payload)


def test_non_boolean_review_mode_is_refused_without_running_summary():
    artifact = verify_deidentified_artifact(_synthetic_result())
    calls: list[str] = []

    refused = run_summary_stage(
        artifact,
        lambda _: calls.append("called"),
        human_review_mode=1,
    )

    assert refused.refusal_reasons == (SUMMARY_REFUSAL_HUMAN_REVIEW,)
    assert calls == []


def test_review_and_diagnostic_flags_are_literal_in_the_public_contract():
    hints = get_type_hints(SummaryEnvelope)
    assert hints["requires_human_review"] == Literal[True]
    assert hints["is_diagnostic"] == Literal[False]
