"""OMOP CDM interoperability helpers."""

from importlib import import_module
from typing import Any

from .cdm_loader import (
    UNMAPPED_CONCEPT_ID,
    UNMAPPED_CONCEPT_NAME,
    UNMAPPED_VOCABULARY_ID,
    LoadMode,
    OmopCdmTables,
    OmopConstraintViolation,
    OmopDomain,
    OmopDownstreamConsumer,
    OmopLoadEvent,
    OmopLoadSummary,
    OmopValidationReport,
    RejectedSpan,
    WriterKind,
    create_omop_schema,
    deterministic_note_hash,
    deterministic_omop_id,
    emit_postgres_ddl,
    load_grounded_jsonl,
    load_grounded_notes,
    summarize_omop_violations,
    validate_omop_database,
    validate_omop_database_report,
    validate_omop_tables,
    validate_omop_tables_report,
    write_omop_duckdb,
    write_omop_parquet,
    write_omop_sqlite,
)
from .mutation_batch import (
    CommitStatus,
    MutationOperation,
    OmopApprovalBinding,
    OmopBatchCommitter,
    OmopCommitResult,
    OmopMutation,
    OmopMutationBatch,
    OmopMutationError,
    OmopMutationPreview,
    OmopMutationSummary,
    OmopReferenceIssue,
    OmopRowKey,
)
from .vocab_router import (
    MappingStatus,
    SourceToConceptMapping,
    VocabularyRouter,
    domain_cdm_table,
    route_domain,
)
from .vocabulary_write_gate import (
    VOCABULARY_WRITE_GATE_SCHEMA,
    VocabularyCompatibility,
    VocabularyConcept,
    VocabularyGateDecision,
    VocabularyMappingProvenance,
    VocabularyRemappingRequest,
    VocabularySnapshot,
    VocabularyWriteGate,
    VocabularyWriteGateError,
    VocabularyWriteGateReport,
)

_FACT_PROJECTION_EXPORTS = frozenset(
    {
        "OMOP_DATASET_SPLITS",
        "OMOP_DOMAIN_TABLES",
        "OMOP_FACT_PROJECTION_CDM_VERSION",
        "OMOP_FACT_PROJECTION_COMPATIBILITY_POLICY",
        "OMOP_FACT_PROJECTION_MODES",
        "OMOP_FACT_PROJECTION_SCHEMA_NAME",
        "OMOP_FACT_PROJECTION_SCHEMA_VERSION",
        "OMOP_FACT_PROJECTOR_VERSION",
        "OMOP_FACT_TABLES",
        "OMOP_MAPPING_STATES",
        "OMOP_PERMISSIVE_LICENSES",
        "OmopConceptMapping",
        "OmopEtlRun",
        "OmopFactProjection",
        "OmopFactProjectionConflictError",
        "OmopFactProjectionDeniedError",
        "OmopFactProjectionError",
        "OmopFactProjectionInput",
        "OmopFactProjectionUnsupportedError",
        "OmopFactRoundTripReport",
        "OmopMappingOutcome",
        "OmopProjectionLoss",
        "OmopProjectionSummary",
        "OmopProjectionViolation",
        "OmopRowProvenance",
        "OmopVocabularySnapshot",
        "assess_omop_fact_round_trip",
        "load_omop_fact_projection_schema",
        "project_clinical_facts_to_omop",
        "validate_omop_fact_projection",
    }
)

_QUALITY_EXPORTS = frozenset(
    {
        "OMOP_QUALITY_CATEGORIES",
        "OMOP_QUALITY_CHECK_STATUSES",
        "OMOP_QUALITY_COMPATIBILITY_POLICY",
        "OMOP_QUALITY_EXECUTION_MODES",
        "OMOP_QUALITY_PERMISSIVE_LICENSES",
        "OMOP_QUALITY_REPORT_ARTIFACT",
        "OMOP_QUALITY_REPORT_SCHEMA_VERSION",
        "OMOP_QUALITY_SEVERITIES",
        "OMOP_QUALITY_SIGNATURE_ALGORITHM",
        "OMOP_QUALITY_VERDICTS",
        "OmopProjectionAggregate",
        "OmopQualityCategorySummary",
        "OmopQualityCheck",
        "OmopQualityConflictError",
        "OmopQualityDeniedError",
        "OmopQualityError",
        "OmopQualityInput",
        "OmopQualityProtocolError",
        "OmopQualityReport",
        "OmopQualitySignature",
        "OmopQualityUnsupportedError",
        "OmopReconciliation",
        "OmopRowCountDelta",
        "build_omop_quality_tool_output",
        "load_omop_quality_report_schema",
        "normalize_omop_quality_output",
        "projection_quality_checks",
        "reconcile_omop_aggregates",
        "run_omop_quality_remote",
        "run_omop_quality_subprocess",
        "sign_omop_quality_report",
        "verify_omop_quality_report",
    }
)


def __getattr__(name: str) -> Any:
    """Load newer OMOP contracts without widening import cycles."""

    if name in _FACT_PROJECTION_EXPORTS:
        module_name = ".fact_projection"
    elif name in _QUALITY_EXPORTS:
        module_name = ".quality"
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "OMOP_DATASET_SPLITS",
    "OMOP_DOMAIN_TABLES",
    "OMOP_FACT_PROJECTION_CDM_VERSION",
    "OMOP_FACT_PROJECTION_COMPATIBILITY_POLICY",
    "OMOP_FACT_PROJECTION_MODES",
    "OMOP_FACT_PROJECTION_SCHEMA_NAME",
    "OMOP_FACT_PROJECTION_SCHEMA_VERSION",
    "OMOP_FACT_PROJECTOR_VERSION",
    "OMOP_FACT_TABLES",
    "OMOP_MAPPING_STATES",
    "OMOP_PERMISSIVE_LICENSES",
    "OMOP_QUALITY_CATEGORIES",
    "OMOP_QUALITY_CHECK_STATUSES",
    "OMOP_QUALITY_COMPATIBILITY_POLICY",
    "OMOP_QUALITY_EXECUTION_MODES",
    "OMOP_QUALITY_PERMISSIVE_LICENSES",
    "OMOP_QUALITY_REPORT_ARTIFACT",
    "OMOP_QUALITY_REPORT_SCHEMA_VERSION",
    "OMOP_QUALITY_SEVERITIES",
    "OMOP_QUALITY_SIGNATURE_ALGORITHM",
    "OMOP_QUALITY_VERDICTS",
    "LoadMode",
    "MappingStatus",
    "CommitStatus",
    "MutationOperation",
    "OmopApprovalBinding",
    "OmopBatchCommitter",
    "OmopCommitResult",
    "OmopCdmTables",
    "OmopConceptMapping",
    "OmopConstraintViolation",
    "OmopDownstreamConsumer",
    "OmopDomain",
    "OmopLoadEvent",
    "OmopLoadSummary",
    "OmopEtlRun",
    "OmopFactProjection",
    "OmopFactProjectionConflictError",
    "OmopFactProjectionDeniedError",
    "OmopFactProjectionError",
    "OmopFactProjectionInput",
    "OmopFactProjectionUnsupportedError",
    "OmopFactRoundTripReport",
    "OmopMappingOutcome",
    "OmopProjectionAggregate",
    "OmopProjectionLoss",
    "OmopProjectionSummary",
    "OmopProjectionViolation",
    "OmopQualityCategorySummary",
    "OmopQualityCheck",
    "OmopQualityConflictError",
    "OmopQualityDeniedError",
    "OmopQualityError",
    "OmopQualityInput",
    "OmopQualityProtocolError",
    "OmopQualityReport",
    "OmopQualitySignature",
    "OmopQualityUnsupportedError",
    "OmopReconciliation",
    "OmopRowProvenance",
    "OmopRowCountDelta",
    "OmopVocabularySnapshot",
    "OmopMutation",
    "OmopMutationBatch",
    "OmopMutationError",
    "OmopMutationPreview",
    "OmopMutationSummary",
    "OmopReferenceIssue",
    "OmopRowKey",
    "OmopValidationReport",
    "RejectedSpan",
    "SourceToConceptMapping",
    "UNMAPPED_CONCEPT_ID",
    "UNMAPPED_CONCEPT_NAME",
    "UNMAPPED_VOCABULARY_ID",
    "VocabularyRouter",
    "VOCABULARY_WRITE_GATE_SCHEMA",
    "VocabularyCompatibility",
    "VocabularyConcept",
    "VocabularyGateDecision",
    "VocabularyMappingProvenance",
    "VocabularyRemappingRequest",
    "VocabularySnapshot",
    "VocabularyWriteGate",
    "VocabularyWriteGateError",
    "VocabularyWriteGateReport",
    "WriterKind",
    "assess_omop_fact_round_trip",
    "build_omop_quality_tool_output",
    "create_omop_schema",
    "deterministic_note_hash",
    "deterministic_omop_id",
    "domain_cdm_table",
    "emit_postgres_ddl",
    "load_grounded_jsonl",
    "load_grounded_notes",
    "load_omop_fact_projection_schema",
    "load_omop_quality_report_schema",
    "normalize_omop_quality_output",
    "project_clinical_facts_to_omop",
    "projection_quality_checks",
    "reconcile_omop_aggregates",
    "route_domain",
    "run_omop_quality_remote",
    "run_omop_quality_subprocess",
    "sign_omop_quality_report",
    "summarize_omop_violations",
    "validate_omop_database",
    "validate_omop_database_report",
    "validate_omop_fact_projection",
    "validate_omop_tables",
    "validate_omop_tables_report",
    "verify_omop_quality_report",
    "write_omop_duckdb",
    "write_omop_parquet",
    "write_omop_sqlite",
]
