"""Third-party extension SDK for OpenMed plugin components."""

from __future__ import annotations

from .protocols import (
    COMPONENT_ANONYMIZER_PROVIDER,
    COMPONENT_EXPORTER,
    COMPONENT_INTEROP_ADAPTER,
    COMPONENT_LANGUAGE_PACK,
    COMPONENT_RECOGNIZER,
    PLUGIN_COMPONENT_KINDS,
    PLUGIN_SDK_MAJOR,
    PLUGIN_SDK_VERSION,
    AnonymizerProviderPlugin,
    ExporterPlugin,
    InteropAdapterPlugin,
    LanguagePackPlugin,
    PluginComponent,
    PluginComponentMetadata,
    RecognizerPlugin,
)
from .registry import (
    PERMISSIVE_LICENSES,
    PLUGIN_ENTRY_POINT_GROUP,
    PluginDiscoveryPolicy,
    PluginDiscoveryResult,
    PluginQuarantineRecord,
    PluginRegistration,
    PluginRegistry,
    discover_plugins,
    is_permissive_license,
    iter_plugins,
    quarantined_plugins,
)

__all__ = [
    "COMPONENT_ANONYMIZER_PROVIDER",
    "COMPONENT_EXPORTER",
    "COMPONENT_INTEROP_ADAPTER",
    "COMPONENT_LANGUAGE_PACK",
    "COMPONENT_RECOGNIZER",
    "PERMISSIVE_LICENSES",
    "PLUGIN_COMPONENT_KINDS",
    "PLUGIN_ENTRY_POINT_GROUP",
    "PLUGIN_SDK_MAJOR",
    "PLUGIN_SDK_VERSION",
    "AnonymizerProviderPlugin",
    "ExporterPlugin",
    "InteropAdapterPlugin",
    "LanguagePackPlugin",
    "PluginComponent",
    "PluginComponentMetadata",
    "PluginDiscoveryPolicy",
    "PluginDiscoveryResult",
    "PluginQuarantineRecord",
    "PluginRegistration",
    "PluginRegistry",
    "RecognizerPlugin",
    "discover_plugins",
    "is_permissive_license",
    "iter_plugins",
    "quarantined_plugins",
]
