"""Partition-safe Spark redaction for selected string columns.

This module defines a small contract around Spark's ``mapPartitions`` API
without importing PySpark.  :class:`SparkRedactionTransform` contains only an
immutable, pickle-safe configuration.  A redaction callable is constructed
inside each partition, so a mutable model, surrogate map, or other worker
state is never created on the driver or shared between executors.

The local :func:`redact_partition` harness is intentionally usable without
Spark.  It is useful for testing the serialization and retry contract with a
synthetic deidentifier before submitting a job.  The default deidentifier is
configured for cache-only model loading; callers must stage model artifacts
on each worker before running an offline job.

Raw source values are never interpolated into exceptions or logs generated by
this module.  Partition failures are reported with stable contract metadata
only because Spark commonly forwards worker exception text to driver logs.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Final, TypeAlias

Deidentifier = Callable[..., Any]
PartitionDeidentifierFactory = Callable[[], Deidentifier]

_DEFAULT_METHOD: Final[str] = "mask"
_DEFAULT_POLICY: Final[str] = "hipaa_safe_harbor"
_DEFAULT_CONFIDENCE_THRESHOLD: Final[float] = 0.7
_DEFAULT_SEED: Final[int] = 0
_MAX_EXTRA_DEPTH: Final[int] = 16
_MAX_EXTRA_ITEMS: Final[int] = 4096
_MAX_EXTRA_LEAF_SIZE: Final[int] = 1_048_576

_FrozenExtraValue: TypeAlias = tuple[str, Any]

_RESERVED_KWARGS: Final[frozenset[str]] = frozenset(
    {
        "audit",
        "budget",
        "cache_results",
        "config",
        "consistent",
        "custom_recognizer",
        "keep_mapping",
        "lid_model",
        "loader",
        "max_cache_entries",
        "method",
        "model_name",
        "policy",
        "seed",
        "surrogate_vault",
        "text",
        "transliterated_name_config",
    }
)


class SparkRedactionError(RuntimeError):
    """Raised when a Spark redaction contract cannot be completed."""


_VALUE_FREE_SPARK_ERROR_MESSAGES: Final[frozenset[str]] = frozenset(
    {
        "Spark DataFrame redaction failed",
        "Spark partition redaction failed for the configured columns",
        "Spark row is missing a configured text column",
        "configured Spark columns must contain strings or nulls",
        "dataframe is missing a configured text column",
        "deidentifier must return text or deidentified_text",
        "partition deidentifier failed",
    }
)


def _is_value_free_spark_error(error: SparkRedactionError) -> bool:
    """Return whether an exact contract error contains one approved message."""

    return (
        type(error) is SparkRedactionError
        and len(error.args) == 1
        and type(error.args[0]) is str
        and error.args[0] in _VALUE_FREE_SPARK_ERROR_MESSAGES
    )


@dataclass(frozen=True, init=False)
class SparkRedactionConfig:
    """Immutable settings shipped to every Spark partition.

    ``columns`` and ``text_columns`` are accepted as aliases.  The normalized
    configuration stores column names as a tuple and extra keyword arguments
    as sorted key/value pairs, making the object safe to pickle and compare.
    No callable, model loader, or surrogate store belongs in this object.

    Args:
        columns: Selected nullable string columns to redact.
        text_columns: Alias for ``columns``.
        method: OpenMed de-identification method.  ``"mask"`` is the
            deterministic default.
        policy: OpenMed policy profile.
        model_name: Optional local model identifier.
        confidence_threshold: Detection threshold forwarded to OpenMed.
        seed: Request seed for deterministic replacement or date shifting.
        consistent: Request stable replacements within each input value.
        extra_kwargs: Additional immutable data options forwarded to OpenMed.
        deidentify_kwargs: Alias for ``extra_kwargs``.
    """

    columns: tuple[str, ...]
    method: str
    policy: str
    model_name: str | None
    confidence_threshold: float
    seed: int
    consistent: bool
    _extra_items: tuple[tuple[str, _FrozenExtraValue], ...] = field(repr=False)

    def __init__(
        self,
        columns: Sequence[str] | None = None,
        *,
        text_columns: Sequence[str] | None = None,
        method: str = _DEFAULT_METHOD,
        policy: str = _DEFAULT_POLICY,
        model_name: str | None = None,
        confidence_threshold: float = _DEFAULT_CONFIDENCE_THRESHOLD,
        seed: int = _DEFAULT_SEED,
        consistent: bool = True,
        extra_kwargs: Mapping[str, Any] | None = None,
        deidentify_kwargs: Mapping[str, Any] | None = None,
    ) -> None:
        if columns is not None and text_columns is not None:
            raise TypeError("provide columns or text_columns, not both")
        selected = columns if columns is not None else text_columns
        normalized_columns = _normalize_columns(selected)

        if type(method) is not str or not method.strip():
            raise ValueError("method must be a non-empty string")
        if type(policy) is not str or not policy.strip():
            raise ValueError("policy must be a non-empty string")
        if model_name is not None and (
            type(model_name) is not str or not model_name.strip()
        ):
            raise ValueError("model_name must be a non-empty string")
        if type(confidence_threshold) not in (int, float):
            raise TypeError("confidence_threshold must be a number")
        if not 0 <= confidence_threshold <= 1:
            raise ValueError("confidence_threshold must be between 0 and 1")
        if type(seed) is not int:
            raise TypeError("seed must be an integer")
        if type(consistent) is not bool:
            raise TypeError("consistent must be a boolean")

        if extra_kwargs is not None and deidentify_kwargs is not None:
            raise TypeError("provide extra_kwargs or deidentify_kwargs, not both")
        supplied_kwargs = (
            extra_kwargs if extra_kwargs is not None else deidentify_kwargs
        )
        extra_items = _normalize_extra_kwargs(supplied_kwargs)

        object.__setattr__(self, "columns", normalized_columns)
        object.__setattr__(self, "method", method.strip())
        object.__setattr__(self, "policy", policy.strip())
        object.__setattr__(
            self, "model_name", model_name.strip() if model_name else None
        )
        object.__setattr__(self, "confidence_threshold", float(confidence_threshold))
        object.__setattr__(self, "seed", seed)
        object.__setattr__(self, "consistent", consistent)
        object.__setattr__(self, "_extra_items", extra_items)

    @property
    def text_columns(self) -> tuple[str, ...]:
        """Return the selected columns under the database-style alias."""

        return self.columns

    @property
    def extra_kwargs(self) -> dict[str, Any]:
        """Return a copy of additional deidentifier keyword arguments."""

        if type(self._extra_items) is not tuple:
            raise TypeError("stored extra kwargs are invalid")

        restored: dict[str, Any] = {}
        for item in self._extra_items:
            if type(item) is not tuple or len(item) != 2:
                raise TypeError("stored extra kwargs are invalid")
            key, frozen = item
            if type(key) is not str or not key or key in restored:
                raise TypeError("stored extra kwargs are invalid")
            restored[key] = _thaw_extra_value(frozen)
        return restored

    def to_deidentify_kwargs(self) -> dict[str, Any]:
        """Return deterministic options for one partition-local worker."""

        kwargs: dict[str, Any] = {
            "method": self.method,
            "policy": self.policy,
            "confidence_threshold": self.confidence_threshold,
            "seed": self.seed,
            "consistent": self.consistent,
        }
        if self.model_name is not None:
            kwargs["model_name"] = self.model_name
        kwargs.update(self.extra_kwargs)
        return kwargs


class SparkRedactionTransform:
    """Apply a partition-local redaction contract to a Spark DataFrame.

    The transform stores only :class:`SparkRedactionConfig`.  Use
    ``deidentifier_factory`` on :meth:`redact_partition` or :meth:`apply` only
    for a top-level, serializable worker factory or an offline test double.
    The factory is called once for each partition attempt; Spark retries create
    a fresh worker instance rather than sharing mutable state across attempts.

    Args:
        columns: Selected columns, or a complete configuration as the first
            positional argument.
        config: Complete configuration.  It cannot be combined with column
            arguments.
        text_columns: Alias for ``columns``.
        **config_kwargs: Keyword arguments accepted by
            :class:`SparkRedactionConfig`.
    """

    def __init__(
        self,
        columns: Sequence[str] | SparkRedactionConfig | None = None,
        *,
        config: SparkRedactionConfig | None = None,
        text_columns: Sequence[str] | None = None,
        **config_kwargs: Any,
    ) -> None:
        if isinstance(columns, SparkRedactionConfig):
            if config is not None or text_columns is not None or config_kwargs:
                raise TypeError("configuration cannot be combined with other options")
            config = columns
            columns = None
        elif config is not None and (
            columns is not None or text_columns is not None or config_kwargs
        ):
            raise TypeError("config cannot be combined with column options")

        self.config = config or SparkRedactionConfig(
            columns,
            text_columns=text_columns,
            **config_kwargs,
        )

    @property
    def columns(self) -> tuple[str, ...]:
        """Return the configured text columns."""

        return self.config.columns

    @property
    def text_columns(self) -> tuple[str, ...]:
        """Return the configured text columns under the alias."""

        return self.config.text_columns

    def redact_partition(
        self,
        rows: Iterable[Any],
        *,
        partition_id: int = 0,
        deidentifier_factory: PartitionDeidentifierFactory | None = None,
    ) -> Iterator[dict[str, Any]]:
        """Return a lazy iterator that redacts one partition of row mappings."""

        return redact_partition(
            rows,
            self.config,
            partition_id=partition_id,
            deidentifier_factory=deidentifier_factory,
        )

    def map_partition(
        self,
        rows: Iterable[Any],
        *,
        partition_id: int = 0,
        deidentifier_factory: PartitionDeidentifierFactory | None = None,
    ) -> Iterator[dict[str, Any]]:
        """Alias for :meth:`redact_partition` for map-partitions callers."""

        return self.redact_partition(
            rows,
            partition_id=partition_id,
            deidentifier_factory=deidentifier_factory,
        )

    def apply(
        self,
        dataframe: Any,
        *,
        deidentifier_factory: PartitionDeidentifierFactory | None = None,
    ) -> Any:
        """Return a Spark DataFrame with the configured columns redacted.

        PySpark is resolved by the caller's DataFrame and is never imported by
        this module.  The closure submitted to Spark captures only this
        immutable configuration and an optional serializable factory.
        """

        _validate_dataframe_columns(dataframe, self.columns)
        try:
            rdd = getattr(dataframe, "rdd", None)
            map_with_index = getattr(rdd, "mapPartitionsWithIndex", None)
            session = getattr(dataframe, "sparkSession", None)
            create_dataframe = getattr(session, "createDataFrame", None)
        except Exception:
            raise TypeError(
                "dataframe must expose rdd.mapPartitionsWithIndex() and "
                "sparkSession.createDataFrame()"
            ) from None
        if not callable(map_with_index) or not callable(create_dataframe):
            raise TypeError(
                "dataframe must expose rdd.mapPartitionsWithIndex() and "
                "sparkSession.createDataFrame()"
            )

        config = self.config

        def _map_partition(
            partition_id: int,
            rows: Iterable[Any],
        ) -> Iterator[dict[str, Any]]:
            return redact_partition(
                rows,
                config,
                partition_id=partition_id,
                deidentifier_factory=deidentifier_factory,
            )

        try:
            redacted_rdd = map_with_index(_map_partition)
            return create_dataframe(redacted_rdd, schema=dataframe.schema)
        except SparkRedactionError as error:
            if _is_value_free_spark_error(error):
                raise
            raise SparkRedactionError("Spark DataFrame redaction failed") from None
        except Exception:
            raise SparkRedactionError("Spark DataFrame redaction failed") from None

    transform = apply

    def __call__(
        self,
        dataframe: Any,
        *,
        deidentifier_factory: PartitionDeidentifierFactory | None = None,
    ) -> Any:
        """Apply the transform as a callable DataFrame operation."""

        return self.apply(dataframe, deidentifier_factory=deidentifier_factory)


def redact_partition(
    rows: Iterable[Any],
    config: SparkRedactionConfig | SparkRedactionTransform,
    *,
    partition_id: int = 0,
    deidentifier_factory: PartitionDeidentifierFactory | None = None,
) -> Iterator[dict[str, Any]]:
    """Redact one partition without requiring Spark.

    The worker factory is invoked exactly once when iteration starts.  Every
    selected value must be a string or ``None``; all other fields are copied
    unchanged.  Any failure is converted to :class:`SparkRedactionError` with
    a value-free message.
    """

    resolved_config = _coerce_config(config)
    _validate_partition_id(partition_id)

    try:
        worker = (
            _new_partition_deidentifier(resolved_config)
            if deidentifier_factory is None
            else deidentifier_factory()
        )
        if not callable(worker) and not callable(getattr(worker, "deidentify", None)):
            raise TypeError("deidentifier_factory must return a callable worker")
        deidentify_kwargs = resolved_config.to_deidentify_kwargs()

        for row in rows:
            output = _row_mapping(row)
            for column in resolved_config.columns:
                if column not in output:
                    raise SparkRedactionError(
                        "Spark row is missing a configured text column"
                    )
                value = output[column]
                if value is None:
                    continue
                if not isinstance(value, str):
                    raise SparkRedactionError(
                        "configured Spark columns must contain strings or nulls"
                    )
                result = _invoke_worker(worker, value, deidentify_kwargs)
                output[column] = _result_text(result)
            yield output
    except SparkRedactionError as error:
        if _is_value_free_spark_error(error):
            raise
        raise SparkRedactionError(
            "Spark partition redaction failed for the configured columns"
        ) from None
    except Exception:
        raise SparkRedactionError(
            "Spark partition redaction failed for the configured columns"
        ) from None


def redact_spark_dataframe(
    dataframe: Any,
    columns: Sequence[str] | SparkRedactionConfig | None = None,
    *,
    config: SparkRedactionConfig | None = None,
    text_columns: Sequence[str] | None = None,
    deidentifier_factory: PartitionDeidentifierFactory | None = None,
    **config_kwargs: Any,
) -> Any:
    """Redact selected columns on a Spark DataFrame using the contract."""

    return SparkRedactionTransform(
        columns,
        config=config,
        text_columns=text_columns,
        **config_kwargs,
    ).apply(dataframe, deidentifier_factory=deidentifier_factory)


def _coerce_config(
    config: SparkRedactionConfig | SparkRedactionTransform,
) -> SparkRedactionConfig:
    if isinstance(config, SparkRedactionTransform):
        return config.config
    if isinstance(config, SparkRedactionConfig):
        return config
    raise TypeError("config must be a SparkRedactionConfig or transform")


def _normalize_columns(columns: Sequence[str] | None) -> tuple[str, ...]:
    if columns is None or isinstance(columns, (str, bytes)):
        raise TypeError("columns must be a sequence of column names")
    try:
        values = tuple(columns)
    except Exception:
        raise TypeError("columns must be a sequence of column names") from None
    if not values:
        raise ValueError("columns must contain at least one column")

    normalized: list[str] = []
    seen: set[str] = set()
    for column in values:
        if type(column) is not str or not column.strip():
            raise ValueError("columns must contain non-empty string names")
        name = column.strip()
        if "\x00" in name:
            raise ValueError("columns must contain valid string names")
        if name in seen:
            raise ValueError("columns must not contain duplicates")
        normalized.append(name)
        seen.add(name)
    return tuple(normalized)


def _normalize_extra_kwargs(
    values: Mapping[str, Any] | None,
) -> tuple[tuple[str, _FrozenExtraValue], ...]:
    if values is None:
        return ()
    if not isinstance(values, Mapping):
        raise TypeError("extra kwargs must be a mapping")

    try:
        supplied_items = tuple(values.items())
    except Exception:
        raise TypeError("extra kwargs could not be read") from None

    normalized: list[tuple[str, _FrozenExtraValue]] = []
    item_budget = [0]
    for supplied_item in supplied_items:
        if type(supplied_item) not in (tuple, list) or len(supplied_item) != 2:
            raise TypeError("extra kwargs could not be read")
        key, value = supplied_item
        if type(key) is not str or not key:
            raise TypeError("extra kwargs keys must be non-empty strings")
        if len(key) > _MAX_EXTRA_LEAF_SIZE:
            raise TypeError("extra kwargs keys exceed the supported size")
        if key in _RESERVED_KWARGS:
            raise ValueError("extra kwargs must not override reserved keys")
        frozen = _freeze_extra_value(
            value,
            depth=0,
            active_ids=set(),
            item_budget=item_budget,
        )
        normalized.append((key, frozen))
    return tuple(sorted(normalized, key=lambda item: item[0]))


def _freeze_extra_value(
    value: Any,
    *,
    depth: int,
    active_ids: set[int],
    item_budget: list[int],
) -> _FrozenExtraValue:
    """Convert supported configuration data to an immutable safe snapshot."""

    item_budget[0] += 1
    if depth > _MAX_EXTRA_DEPTH or item_budget[0] > _MAX_EXTRA_ITEMS:
        raise TypeError("extra kwargs values exceed the supported complexity")

    value_type = type(value)
    if value is None:
        return ("none", None)
    if value_type is bool:
        return ("bool", value)
    if value_type is int:
        return ("int", value)
    if value_type is float:
        if not math.isfinite(value):
            raise TypeError("extra kwargs values must contain finite numbers")
        return ("float", value)
    if value_type is str:
        if len(value) > _MAX_EXTRA_LEAF_SIZE:
            raise TypeError("extra kwargs values exceed the supported size")
        return ("str", value)
    if value_type is bytes:
        if len(value) > _MAX_EXTRA_LEAF_SIZE:
            raise TypeError("extra kwargs values exceed the supported size")
        return ("bytes", value)
    if isinstance(value, Path):
        try:
            rendered = str(value)
        except Exception:
            raise TypeError("extra kwargs path value could not be read") from None
        if len(rendered) > _MAX_EXTRA_LEAF_SIZE:
            raise TypeError("extra kwargs values exceed the supported size")
        return ("path", rendered)

    if value_type not in (list, tuple, dict):
        raise TypeError("extra kwargs values must use supported data types")

    object_id = id(value)
    if object_id in active_ids:
        raise TypeError("extra kwargs values must not contain cycles")
    active_ids.add(object_id)
    try:
        if value_type in (list, tuple):
            frozen_values = tuple(
                _freeze_extra_value(
                    item,
                    depth=depth + 1,
                    active_ids=active_ids,
                    item_budget=item_budget,
                )
                for item in value
            )
            return ("list" if value_type is list else "tuple", frozen_values)

        frozen_items: list[tuple[str, _FrozenExtraValue]] = []
        for key, item in value.items():
            if type(key) is not str:
                raise TypeError("nested extra kwargs mappings require string keys")
            if len(key) > _MAX_EXTRA_LEAF_SIZE:
                raise TypeError("extra kwargs values exceed the supported size")
            frozen_items.append(
                (
                    key,
                    _freeze_extra_value(
                        item,
                        depth=depth + 1,
                        active_ids=active_ids,
                        item_budget=item_budget,
                    ),
                )
            )
        return ("dict", tuple(sorted(frozen_items, key=lambda item: item[0])))
    finally:
        active_ids.remove(object_id)


def _thaw_extra_value(frozen: _FrozenExtraValue) -> Any:
    """Return a fresh value from an internally generated safe snapshot."""

    if type(frozen) is not tuple or len(frozen) != 2:
        raise TypeError("stored extra kwargs are invalid")
    tag, payload = frozen
    if type(tag) is not str:
        raise TypeError("stored extra kwargs are invalid")

    if tag == "none" and payload is None:
        return None
    if tag == "bool" and type(payload) is bool:
        return payload
    if tag == "int" and type(payload) is int:
        return payload
    if tag == "float" and type(payload) is float and math.isfinite(payload):
        return payload
    if tag == "str" and type(payload) is str:
        return payload
    if tag == "bytes" and type(payload) is bytes:
        return payload
    if tag == "path" and type(payload) is str:
        return Path(payload)
    if tag in ("list", "tuple") and type(payload) is tuple:
        values = tuple(_thaw_extra_value(item) for item in payload)
        return list(values) if tag == "list" else values
    if tag == "dict" and type(payload) is tuple:
        restored: dict[str, Any] = {}
        for item in payload:
            if type(item) is not tuple or len(item) != 2:
                raise TypeError("stored extra kwargs are invalid")
            key, value = item
            if type(key) is not str or key in restored:
                raise TypeError("stored extra kwargs are invalid")
            restored[key] = _thaw_extra_value(value)
        return restored
    raise TypeError("stored extra kwargs are invalid")


def _validate_partition_id(partition_id: int) -> None:
    if type(partition_id) is not int:
        raise TypeError("partition_id must be an integer")
    if partition_id < 0:
        raise ValueError("partition_id must be non-negative")


def _validate_dataframe_columns(dataframe: Any, columns: Sequence[str]) -> None:
    try:
        available = getattr(dataframe, "columns", None)
    except Exception:
        raise TypeError("dataframe must expose a sequence of columns") from None
    if isinstance(available, (str, bytes)) or available is None:
        raise TypeError("dataframe must expose a sequence of columns")
    try:
        available_set = set(available)
    except Exception:
        raise TypeError("dataframe must expose a sequence of columns") from None
    try:
        missing_column = any(column not in available_set for column in columns)
    except Exception:
        raise TypeError("dataframe must expose a sequence of columns") from None
    if missing_column:
        raise SparkRedactionError("dataframe is missing a configured text column")


def _row_mapping(row: Any) -> dict[str, Any]:
    if isinstance(row, Mapping):
        return dict(row)

    as_dict = getattr(row, "asDict", None)
    if callable(as_dict):
        try:
            value = as_dict(recursive=True)
        except TypeError:
            value = as_dict()
        if isinstance(value, Mapping):
            return dict(value)

    named_values = getattr(row, "_asdict", None)
    if callable(named_values):
        value = named_values()
        if isinstance(value, Mapping):
            return dict(value)

    raise TypeError("Spark rows must expose a mapping-compatible shape")


def _invoke_worker(
    worker: Any,
    value: str,
    kwargs: Mapping[str, Any],
) -> Any:
    try:
        if callable(worker):
            return worker(value, **dict(kwargs))
        return worker.deidentify(value, **dict(kwargs))
    except Exception:
        raise SparkRedactionError("partition deidentifier failed") from None


def _result_text(result: Any) -> str:
    if isinstance(result, str):
        return result
    if isinstance(result, Mapping):
        redacted = result.get("deidentified_text")
    else:
        redacted = getattr(result, "deidentified_text", None)
    if not isinstance(redacted, str):
        raise SparkRedactionError("deidentifier must return text or deidentified_text")
    return redacted


def _new_partition_deidentifier(config: SparkRedactionConfig) -> Deidentifier:
    """Build one cache-only OpenMed worker-local deidentifier."""

    from openmed.core import ModelLoader, OpenMedConfig
    from openmed.core.pii import deidentify

    runtime_config = OpenMedConfig(local_only=True)
    loader = ModelLoader(runtime_config)
    kwargs = config.to_deidentify_kwargs()

    def _redact(text: str, **_: Any) -> Any:
        return deidentify(
            text,
            config=runtime_config,
            loader=loader,
            **kwargs,
        )

    return _redact


_redact_partition = redact_partition


__all__ = [
    "Deidentifier",
    "PartitionDeidentifierFactory",
    "SparkRedactionConfig",
    "SparkRedactionError",
    "SparkRedactionTransform",
    "redact_partition",
    "redact_spark_dataframe",
]
