"""Clinical relation extraction public API."""

from importlib import import_module

from .assertion_filter import (
    ASSERTION_FILTER_ADVISORY,
    RELATION_ASSERTION_STATUSES,
    RELATION_CONDITIONAL,
    RELATION_CONFIRMED,
    RELATION_POSSIBLE,
    RELATION_REFUTED,
    RelationAssertion,
    filter_asserted_relations,
    propagate_relation_assertion,
)
from .candidate import (
    ATTRIBUTE_RELATION_TYPES,
    DRUG_TO_DOSE,
    DRUG_TO_DURATION,
    DRUG_TO_FORM,
    DRUG_TO_FREQUENCY,
    DRUG_TO_INDICATION,
    DRUG_TO_ROUTE,
    DRUG_TO_STRENGTH,
    PROBLEM_ATTRIBUTE_RELATION_TYPES,
    RELATION_ATTRIBUTE_TYPES,
    RELATION_ORDER,
    RELATION_SCHEMA_VERSION,
    CoreferenceProvenance,
    CoreferenceSourceReference,
    JointSpanCandidate,
    MedicationAttributeType,
    MedicationRelation,
    MedicationRelationGroup,
    MedicationRelationType,
    ProblemAttributeType,
    ProblemRelationType,
    Relation,
    RelationAttributeType,
    RelationCandidate,
    RelationCandidateBatch,
    RelationCandidateRule,
    RelationType,
    SpanPairCandidate,
    SpanReference,
    build_relation_candidates,
    enumerate_joint_span_candidates,
    enumerate_span_pair_candidates,
    sample_negative_span_pairs,
    split_sentence_offsets,
)
from .document_level import (
    DOCUMENT_RELATION_ADVISORY,
    DOCUMENT_RELATION_SCHEMA_VERSION,
    DocumentLevelRelation,
    MentionPairEvidence,
    SafeRelationMention,
    aggregate_document_relations,
    extract_document_relations,
)
from .family_history import (
    FAMILY_HISTORY_RELATION_ADVISORY,
    FAMILY_HISTORY_RELATION_TYPE,
    RELATION_TO_PATIENT,
    FamilyHistoryRelation,
    extract_family_history_relations,
)
from .joint_head import (
    JOINT_HEAD_SCHEMA_VERSION,
    JointEntityScore,
    JointHeadConfig,
    JointHeadMode,
    JointHeadOutput,
    JointSpanPairHead,
    JointSpanPairScore,
    decode_joint_span_pairs,
)
from .lab_results import LAB_RESULT_ADVISORY, LabResult, extract_lab_results
from .medication_links import (
    MEDICATION_LINK_ADVISORY,
    MedicationRelationScorer,
    MedicationStatementRecord,
    extract_medication_relations,
    extract_relations,
    link_medication_attributes,
    reconstruct_medication_statements,
)
from .multilingual import (
    CMEIE_ENTITY_TYPES,
    CMEIE_RELATION_MAPPING,
    INDIC_RELATION_MAPPING,
    MULTILINGUAL_RELATION_ADVISORY,
    MULTILINGUAL_RELATION_REGISTRY_VERSION,
    RELATION_TYPE_REGISTRY,
    MultilingualRelation,
    available_multilingual_relation_languages,
    map_relation_type,
    multilingual_relation_rules,
    relation_type_mapping,
)
from .problem_links import (
    PROBLEM_RELATION_ADVISORY,
    PROBLEM_STATUS_CUES,
    extract_problem_relations,
)
from .temporal import (
    TEMPORAL_GRAPH_SCHEMA_VERSION,
    TEMPORAL_RELATION_SCHEMA_VERSION,
    TEMPORAL_RELATION_TYPES,
    TemporalCueReference,
    TemporalRelationCandidate,
    TemporalRelationType,
    TemporalSpanReference,
    TemporalSpanRole,
    decode_tlink_candidates,
    extract_tlink_candidates,
)

__all__ = [
    "ASSERTION_FILTER_ADVISORY",
    "RELATION_ASSERTION_STATUSES",
    "RELATION_CONFIRMED",
    "RELATION_REFUTED",
    "RELATION_CONDITIONAL",
    "RELATION_POSSIBLE",
    "RelationAssertion",
    "propagate_relation_assertion",
    "filter_asserted_relations",
    "ATTRIBUTE_RELATION_TYPES",
    "DRUG_TO_DOSE",
    "DRUG_TO_DURATION",
    "DRUG_TO_FORM",
    "DRUG_TO_FREQUENCY",
    "DRUG_TO_INDICATION",
    "DRUG_TO_ROUTE",
    "DRUG_TO_STRENGTH",
    "PROBLEM_ATTRIBUTE_RELATION_TYPES",
    "DOCUMENT_RELATION_ADVISORY",
    "DOCUMENT_RELATION_SCHEMA_VERSION",
    "FAMILY_HISTORY_RELATION_ADVISORY",
    "FAMILY_HISTORY_RELATION_TYPE",
    "FamilyHistoryRelation",
    "CoreferenceProvenance",
    "CoreferenceSourceReference",
    "DocumentLevelRelation",
    "JOINT_HEAD_SCHEMA_VERSION",
    "JointEntityScore",
    "JointHeadConfig",
    "JointHeadMode",
    "JointHeadOutput",
    "JointSpanCandidate",
    "JointSpanPairHead",
    "JointSpanPairScore",
    "LAB_RESULT_ADVISORY",
    "LabResult",
    "MEDICATION_LINK_ADVISORY",
    "MedicationAttributeType",
    "MedicationRelation",
    "MedicationRelationGroup",
    "MedicationRelationScorer",
    "MedicationStatementRecord",
    "MedicationRelationType",
    "MentionPairEvidence",
    "ProblemAttributeType",
    "ProblemRelationType",
    "PROBLEM_RELATION_ADVISORY",
    "PROBLEM_STATUS_CUES",
    "Relation",
    "RELATION_TO_PATIENT",
    "RelationAttributeType",
    "RELATION_ATTRIBUTE_TYPES",
    "RELATION_ORDER",
    "RELATION_SCHEMA_VERSION",
    "TEMPORAL_GRAPH_SCHEMA_VERSION",
    "TEMPORAL_RELATION_SCHEMA_VERSION",
    "TEMPORAL_RELATION_TYPES",
    "RelationCandidate",
    "RelationCandidateBatch",
    "RelationCandidateRule",
    "RelationType",
    "SpanPairCandidate",
    "SpanReference",
    "SafeRelationMention",
    "TemporalCueReference",
    "TemporalRelationCandidate",
    "TemporalRelationType",
    "TemporalSpanReference",
    "TemporalSpanRole",
    "build_relation_candidates",
    "aggregate_document_relations",
    "decode_joint_span_pairs",
    "decode_tlink_candidates",
    "extract_tlink_candidates",
    "extract_lab_results",
    "extract_medication_relations",
    "extract_document_relations",
    "extract_family_history_relations",
    "extract_problem_relations",
    "enumerate_joint_span_candidates",
    "enumerate_span_pair_candidates",
    "link_medication_attributes",
    "reconstruct_medication_statements",
    "CMEIE_ENTITY_TYPES",
    "CMEIE_RELATION_MAPPING",
    "INDIC_RELATION_MAPPING",
    "MULTILINGUAL_RELATION_ADVISORY",
    "MULTILINGUAL_RELATION_REGISTRY_VERSION",
    "RELATION_TYPE_REGISTRY",
    "MultilingualRelation",
    "available_multilingual_relation_languages",
    "extract_relations",
    "map_relation_type",
    "multilingual_relation_rules",
    "relation_type_mapping",
    "sample_negative_span_pairs",
    "split_sentence_offsets",
    "DEFAULT_MAX_RELATION_ABSTENTION_RATE",
    "DEFAULT_MIN_ISOTONIC_SAMPLES",
    "DEFAULT_MIN_RETAINED_RELATION_ACCURACY",
    "DEFAULT_RELATION_RELIABILITY_BINS",
    "RELATION_CALIBRATION_ADVISORY",
    "RELATION_CALIBRATION_SCHEMA_VERSION",
    "RELATION_STATUS_ASSERTED",
    "RELATION_STATUS_UNCERTAIN",
    "CalibratedRelation",
    "RelationAbstentionResult",
    "RelationCalibrationConsistencyError",
    "RelationCalibrationRecord",
    "RelationCalibrator",
    "RelationOperatingPoint",
    "RelationTypeCalibrator",
    "apply_relation_abstention",
    "assert_relation_consistency_gate",
    "calibrate_relation_scores",
    "coerce_relation_calibration_records",
    "evaluate_relation_consistency_gate",
    "fit_relation_calibrator",
    "relation_calibration_report",
    "select_relation_operating_points",
]

_CALIBRATION_EXPORTS = frozenset(
    {
        "DEFAULT_MAX_RELATION_ABSTENTION_RATE",
        "DEFAULT_MIN_ISOTONIC_SAMPLES",
        "DEFAULT_MIN_RETAINED_RELATION_ACCURACY",
        "DEFAULT_RELATION_RELIABILITY_BINS",
        "RELATION_CALIBRATION_ADVISORY",
        "RELATION_CALIBRATION_SCHEMA_VERSION",
        "RELATION_STATUS_ASSERTED",
        "RELATION_STATUS_UNCERTAIN",
        "CalibratedRelation",
        "RelationAbstentionResult",
        "RelationCalibrationConsistencyError",
        "RelationCalibrationRecord",
        "RelationCalibrator",
        "RelationOperatingPoint",
        "RelationTypeCalibrator",
        "apply_relation_abstention",
        "assert_relation_consistency_gate",
        "calibrate_relation_scores",
        "coerce_relation_calibration_records",
        "evaluate_relation_consistency_gate",
        "fit_relation_calibrator",
        "relation_calibration_report",
        "select_relation_operating_points",
    }
)


def __getattr__(name: str) -> object:
    """Load evaluator-dependent relation calibration exports on demand."""

    if name in _CALIBRATION_EXPORTS:
        calibration = import_module(".calibration", __name__)
        return getattr(calibration, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
