#!/usr/bin/env python3
"""Validate OpenMed Agent Skills and regenerate the catalog + plugin manifest.

A "skill" is a directory under ``skills/`` containing a ``SKILL.md`` file with
YAML frontmatter (``name``, ``description``, optional ``license`` / ``metadata``)
following the open Agent Skills standard (https://agentskills.io) used by both
Claude Code and OpenAI Codex.

Usage:
    python skills/build_catalog.py            # validate + (re)write README + marketplace
    python skills/build_catalog.py --check    # validate only; non-zero exit on any error
    python skills/build_catalog.py --install [claude|codex|all]   # symlink into agent dirs

No third-party dependencies: a tiny frontmatter parser is included so this runs
anywhere, including CI, with the standard library only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

SKILLS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SKILLS_DIR.parent
README = SKILLS_DIR / "README.md"
MARKETPLACE = REPO_ROOT / ".claude-plugin" / "marketplace.json"

NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
RESERVED = ("anthropic", "claude")  # forbidden in skill names per the open spec
# Worker/vendor attribution must never appear in shipped skill text. Match real
# AI-attribution footers, not innocent technical phrasing like "data generated
# by Synthea" or "generated by running a script".
ATTRIB_RE = re.compile(
    r"(co-authored-by|🤖 generated|"
    r"generated (?:with|by) (?:claude|codex|gpt|copilot|cursor|chatgpt|an? ai|ai assistant)|"
    r"written by (?:claude|codex|gpt)|as an ai language model)",
    re.IGNORECASE,
)

CATEGORY_ORDER = [
    "openmed-core",
    "data-ingestion",
    "de-identification",
    "clinical-nlp",
    "terminology-coding",
    "fhir-interop",
    "evaluation-quality",
    "research-genomics",
    "imaging-ocr",
    "compliance-regulatory",
    "safety-pharmacovigilance",
    "analytics-reporting",
    "deployment-ops",
]
CATEGORY_TITLES = {
    "openmed-core": "OpenMed core — build with OpenMed directly",
    "data-ingestion": "Data ingestion — feed clinical text into OpenMed",
    "de-identification": "De-identification & privacy",
    "clinical-nlp": "Clinical NLP — refine OpenMed output",
    "terminology-coding": "Terminology & coding",
    "fhir-interop": "FHIR & interoperability",
    "evaluation-quality": "Evaluation & quality",
    "research-genomics": "Research & genomics",
    "imaging-ocr": "Imaging & OCR intake",
    "compliance-regulatory": "Compliance & regulatory",
    "safety-pharmacovigilance": "Safety & pharmacovigilance",
    "analytics-reporting": "Analytics & reporting",
    "deployment-ops": "Deployment & ops",
}
PAIRS_BADGE = {"before": "→ before", "after": "after →", "adjacent": "↔ adjacent"}


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse a small, predictable subset of YAML frontmatter.

    Supports top-level ``key: value`` pairs and a single nested ``metadata:``
    mapping (one level of indentation). Returns ``(data, body)``.
    """
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end].strip("\n")
    body = text[end + 4 :].lstrip("\n")
    data: dict = {}
    current_map: dict | None = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indented = line[0] in " \t"
        key, _, val = line.strip().partition(":")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if indented and current_map is not None:
            current_map[key] = val
        elif val == "":
            current_map = {}
            data[key] = current_map
        else:
            current_map = None
            data[key] = val
    return data, body


def load_skills() -> tuple[list[dict], list[str]]:
    skills, errors = [], []
    for path in sorted(SKILLS_DIR.iterdir()):
        if not path.is_dir() or path.name.startswith((".", "_")):
            continue
        skill_md = path / "SKILL.md"
        if not skill_md.exists():
            errors.append(f"{path.name}/: missing SKILL.md")
            continue
        text = skill_md.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        name = fm.get("name", "")
        desc = fm.get("description", "")
        meta = fm.get("metadata", {}) if isinstance(fm.get("metadata"), dict) else {}

        if not name:
            errors.append(f"{path.name}/SKILL.md: missing 'name'")
        elif name != path.name:
            errors.append(
                f"{path.name}/SKILL.md: name '{name}' != folder '{path.name}'"
            )
        elif not NAME_RE.match(name):
            errors.append(f"{name}: name must be kebab-case [a-z0-9-]")
        if name and any(w in name for w in RESERVED):
            errors.append(f"{name}: name contains a reserved word {RESERVED}")
        if not desc:
            errors.append(f"{path.name}/SKILL.md: missing 'description'")
        elif len(desc) > 1024:
            errors.append(f"{name}: description >1024 chars ({len(desc)})")
        if ATTRIB_RE.search(text):
            errors.append(f"{name}: contains vendor/worker attribution")
        n_lines = len(body.splitlines())
        if n_lines > 500:
            errors.append(
                f"{name}: SKILL.md body >500 lines ({n_lines}); split into references/"
            )

        skills.append(
            {
                "name": name or path.name,
                "description": desc,
                "category": meta.get("category", "uncategorized"),
                "pairs": meta.get("pairs", ""),
                "path": path,
                "lines": n_lines,
            }
        )
    return skills, errors


def render_readme(skills: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = {}
    for s in skills:
        by_cat.setdefault(s["category"], []).append(s)
    cats = [c for c in CATEGORY_ORDER if c in by_cat]
    cats += sorted(c for c in by_cat if c not in CATEGORY_ORDER)

    out: list[str] = []
    out.append("# OpenMed Skills")
    out.append("")
    out.append(
        "Portable [Agent Skills](https://agentskills.io) for building with "
        "**OpenMed** — the on-device, Apache-2.0 clinical & biomedical NLP "
        "library. Each skill is a folder with a `SKILL.md` that works unchanged "
        "in **Claude Code**, **OpenAI Codex**, **OpenCode**, and any agent on the "
        "open standard. Drop them in and your coding agent learns to wire up "
        "OpenMed pipelines — de-identification, NER, FHIR export, evaluation — "
        "plus the upstream/downstream healthcare tasks around them."
    )
    out.append("")
    out.append(f"**{len(skills)} skills** across {len(cats)} categories.")
    out.append("")
    out.append(
        "## Get running in one command\n\n"
        "The same `SKILL.md` folders work unchanged in **Claude Code**, "
        "**OpenAI Codex**, **OpenCode**, and any agent that follows the "
        "[open standard](https://agentskills.io). Install into every agent you "
        "have at once:\n\n"
        "```bash\n"
        "git clone https://github.com/maziyarpanahi/openmed && cd openmed\n"
        "./install-skills.sh          # -> Claude Code, Codex, OpenCode, and ~/.agents/skills\n"
        "```\n\n"
        "Or target one agent:\n\n"
        "| Agent | Command | Skills directory |\n"
        "| --- | --- | --- |\n"
        "| **Claude Code** | `./install-skills.sh claude` | `~/.claude/skills/` |\n"
        "| **OpenAI Codex** | `./install-skills.sh codex` | `~/.codex/skills/` |\n"
        "| **OpenCode** | `./install-skills.sh opencode` | `~/.config/opencode/skills/` |\n"
        "| **Any other agent** | `./install-skills.sh agents` | `~/.agents/skills/` |\n\n"
        "No clone? Copy the folders directly with `cp -r skills/*/ "
        "~/.claude/skills/` (swap the path per agent). Claude Code users can also "
        "install as a plugin, no clone needed:\n\n"
        "```text\n"
        "/plugin marketplace add maziyarpanahi/openmed\n"
        "/plugin install openmed-skills@openmed-skills\n"
        "```"
    )
    out.append("")
    out.append(
        "## Try it in 30 seconds\n\n"
        "After installing, just ask your agent in plain language — it finds the "
        "right skill and writes correct, on-device OpenMed code for you:\n\n"
        "> **You:** De-identify this discharge note and pull out the medications "
        "with OpenMed — *\"Pt John Doe (MRN 12345), seen 2024-03-02, started on "
        "metformin 500mg BID.\"*\n\n"
        "> **Your agent** loads `deidentifying-clinical-text` + "
        "`extracting-clinical-entities` and produces:\n\n"
        "```python\n"
        "import openmed\n"
        "note = \"Pt John Doe (MRN 12345), seen 2024-03-02, started on metformin 500mg BID.\"\n"
        "deid = openmed.deidentify(note, policy=\"hipaa_safe_harbor\")   # PHI removed on-device\n"
        "meds = openmed.analyze_text(deid.deidentified_text,\n"
        "                            model_name=\"pharma_detection_superclinical\")\n"
        "```\n\n"
        "→ Name, MRN, and date are redacted locally and `metformin 500mg BID` is "
        "returned as a medication entity. No cloud call, no PHI leaves the machine."
    )
    out.append("")
    out.append(
        "New here? Start with **[building-with-openmed]"
        "(building-with-openmed/SKILL.md)** — it maps every task to the right "
        "skill and the real OpenMed API."
    )
    out.append("")
    out.append("## Catalog")
    out.append("")
    out.append(
        "Legend: `→ before` runs upstream of OpenMed, `after →` consumes its "
        "output, `↔ adjacent` is a neighbouring task."
    )
    out.append("")
    for cat in cats:
        out.append(f"### {CATEGORY_TITLES.get(cat, cat)}")
        out.append("")
        out.append("| Skill | What it does | Pairs |")
        out.append("| --- | --- | --- |")
        for s in sorted(by_cat[cat], key=lambda x: x["name"]):
            desc = s["description"].split(". ")[0].rstrip(".")
            if len(desc) > 140:
                desc = desc[:137] + "…"
            badge = PAIRS_BADGE.get(s["pairs"], s["pairs"] or "")
            out.append(f"| [`{s['name']}`]({s['name']}/SKILL.md) | {desc}. | {badge} |")
        out.append("")
    out.append("## Authoring & validation")
    out.append("")
    out.append(
        "Every skill follows the open spec: kebab-case folder name matching "
        "`name`, a `description` that states *what it does and when to use it*, "
        "a body under 500 lines, and detail pushed into `references/`. Validate "
        "and regenerate this catalog with:"
    )
    out.append("")
    out.append("```bash")
    out.append("python skills/build_catalog.py --check   # CI gate")
    out.append(
        "python skills/build_catalog.py           # rewrite README + marketplace"
    )
    out.append("```")
    out.append("")
    return "\n".join(out)


def render_marketplace(skills: list[dict]) -> str:
    payload = {
        "name": "openmed-skills",
        "owner": {"name": "OpenMed", "email": "maziyar@live.co.uk"},
        "metadata": {
            "description": "Skills for building clinical & biomedical NLP pipelines with OpenMed",
            "version": "1.0.0",
        },
        "plugins": [
            {
                "name": "openmed-skills",
                "description": (
                    "De-identify PHI, run clinical NER, export FHIR, evaluate "
                    "with leakage gates, and the healthcare workflows around them."
                ),
                "source": "./",
                "strict": False,
                "skills": [
                    f"./skills/{s['name']}"
                    for s in sorted(skills, key=lambda x: x["name"])
                ],
            }
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def do_install(target: str, skills: list[dict]) -> None:
    home = Path.home()
    dests = []
    if target in ("claude", "all"):
        dests.append(home / ".claude" / "skills")
    if target in ("codex", "all"):
        dests.append(home / ".codex" / "skills")
    for dest in dests:
        dest.mkdir(parents=True, exist_ok=True)
        for s in skills:
            link = dest / s["name"]
            if link.is_symlink() or link.exists():
                if link.is_symlink():
                    link.unlink()
                else:
                    print(f"  skip {link} (exists, not a symlink)")
                    continue
            os.symlink(s["path"], link)
            print(f"  linked {s['name']} -> {link}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="validate only; no writes")
    ap.add_argument(
        "--install", nargs="?", const="all", choices=["claude", "codex", "all"]
    )
    args = ap.parse_args()

    skills, errors = load_skills()
    print(f"Found {len(skills)} skills.")
    if errors:
        print("\nVALIDATION ERRORS:")
        for e in errors:
            print(f"  - {e}")
        return 1
    print("Validation: OK (frontmatter, naming, length, no attribution).")

    if args.install:
        do_install(args.install, skills)
        return 0
    if args.check:
        return 0

    README.write_text(render_readme(skills), encoding="utf-8")
    MARKETPLACE.parent.mkdir(parents=True, exist_ok=True)
    MARKETPLACE.write_text(render_marketplace(skills), encoding="utf-8")
    print(
        f"Wrote {README.relative_to(REPO_ROOT)} and {MARKETPLACE.relative_to(REPO_ROOT)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
