"""FHIR export and offline validation helpers for clinical resources."""

from __future__ import annotations

from .bundle import to_bundle
from .codeable_concept import (
    GROUNDED_CODE_PROVENANCE_EXTENSION_URL,
    MEDICAL_DEVICE_ASSIST_EXTENSION_URL,
    MEDICAL_DEVICE_ASSIST_ONLY_DISCLAIMER,
    POSTCOORDINATED_CODING_PROVENANCE_EXTENSION_URL,
    postcoordinated_codeable_concept,
    stamp_postcoordination_provenance,
    to_codeable_concept,
)
from .condition import (
    CONDITION_CLINICAL_SYSTEM,
    CONDITION_VER_STATUS_SYSTEM,
    to_condition,
)
from .diagnostic_report import (
    DIAGNOSTIC_REPORT_FIELDS_R4R5,
    DIAGNOSTIC_REPORT_STATUS_UNKNOWN,
    DIAGNOSTIC_REPORT_STATUSES,
    to_diagnostic_report,
)
from .exchange import (
    FHIRClinicalExchangeWorkbench,
    FHIRExchange,
    FHIRExchangeError,
    FHIRExchangeWorkbench,
    FHIRValidationError,
    build_clinical_document,
    build_fhir_document,
    build_ipa_example,
    build_ipa_patient_access,
    build_ips_patient_summary,
    build_patient_summary,
    deidentify_bundle,
    deidentify_fhir,
    export_bundle,
    export_fhir,
    import_bundle,
    import_fhir,
    validate_exchange,
)
from .facade import (
    COREFERENCE_EVIDENCE_EXTENSION_URL,
    FHIR_RESOURCE_TYPES,
    FHIRBundle,
    FHIRExportSummary,
    to_fhir,
)
from .observation import to_observation
from .observation_extensions import (
    DEFAULT_OBSERVATION_EXTENSION_RULES,
    FHIR_R4,
    FHIR_R5,
    OBSERVATION_EXTENSION_BASE_URL,
    OBSERVATION_UNKNOWN_STATE_CODES,
    OBSERVATION_UNKNOWN_STATE_EXTENSION_URL,
    ObservationExtensionFinding,
    ObservationExtensionSpec,
    check_observation_extensions,
    validate_observation_extensions,
)
from .operation_outcome import (
    OperationOutcomeIssue,
    from_validation_result,
    to_operation_outcome,
)
from .privacy import (
    INDIA_HEALTH_ID_REDACTION,
    is_india_health_identifier,
    sanitize_india_health_identifiers,
)
from .profile_check import check_bundle
from .profile_declarations import (
    DUPLICATE_PROFILE_DECLARATION,
    MISSING_PROFILE_DECLARATION,
    PROFILE_FHIR_VERSION_MISMATCH,
    PROFILE_RESOURCE_TYPE_MISMATCH,
    PROFILE_VALIDATION_MODE_MISMATCH,
    UNKNOWN_PROFILE_DECLARATION,
    ProfileDeclarationFinding,
    ProfileDeclarationSpec,
    check_profile_declarations,
    validate_profile_declarations,
)
from .provenance import to_audit_event, to_provenance
from .reference_types import (
    FHIR_R4_REFERENCE_TARGETS,
    FHIR_R5_REFERENCE_TARGETS,
    REFERENCE_TARGET_ALLOWLISTS,
    ReferenceTargetIssue,
    check_reference_targets,
    find_reference_target_issues,
    validate_fhir_reference_types,
    validate_reference_targets,
    validate_reference_types,
)
from .references import deterministic_fullurl
from .uscore import US_CORE_VERSION, ConformanceResult, check_us_core
from .validate import (
    BASE_R4_RESOURCE_TYPES,
    ValidationFinding,
    ValidationResult,
    validate_bundle,
    validate_resource,
)

__all__ = [
    "CONDITION_CLINICAL_SYSTEM",
    "CONDITION_VER_STATUS_SYSTEM",
    "COREFERENCE_EVIDENCE_EXTENSION_URL",
    "DUPLICATE_PROFILE_DECLARATION",
    "DEFAULT_OBSERVATION_EXTENSION_RULES",
    "FHIR_R4",
    "FHIR_R5",
    "DIAGNOSTIC_REPORT_FIELDS_R4R5",
    "DIAGNOSTIC_REPORT_STATUS_UNKNOWN",
    "DIAGNOSTIC_REPORT_STATUSES",
    "FHIR_RESOURCE_TYPES",
    "GROUNDED_CODE_PROVENANCE_EXTENSION_URL",
    "MEDICAL_DEVICE_ASSIST_EXTENSION_URL",
    "MEDICAL_DEVICE_ASSIST_ONLY_DISCLAIMER",
    "POSTCOORDINATED_CODING_PROVENANCE_EXTENSION_URL",
    "MISSING_PROFILE_DECLARATION",
    "PROFILE_FHIR_VERSION_MISMATCH",
    "PROFILE_RESOURCE_TYPE_MISMATCH",
    "PROFILE_VALIDATION_MODE_MISMATCH",
    "ProfileDeclarationFinding",
    "ProfileDeclarationSpec",
    "OBSERVATION_EXTENSION_BASE_URL",
    "OBSERVATION_UNKNOWN_STATE_CODES",
    "OBSERVATION_UNKNOWN_STATE_EXTENSION_URL",
    "ObservationExtensionFinding",
    "ObservationExtensionSpec",
    "check_observation_extensions",
    "to_condition",
    "to_diagnostic_report",
    "to_observation",
    "to_codeable_concept",
    "to_fhir",
    "postcoordinated_codeable_concept",
    "stamp_postcoordination_provenance",
    "deterministic_fullurl",
    "OperationOutcomeIssue",
    "INDIA_HEALTH_ID_REDACTION",
    "is_india_health_identifier",
    "sanitize_india_health_identifiers",
    "check_bundle",
    "check_profile_declarations",
    "to_audit_event",
    "from_validation_result",
    "to_bundle",
    "to_operation_outcome",
    "to_provenance",
    "UNKNOWN_PROFILE_DECLARATION",
    "validate_profile_declarations",
    "FHIR_R4_REFERENCE_TARGETS",
    "FHIR_R5_REFERENCE_TARGETS",
    "REFERENCE_TARGET_ALLOWLISTS",
    "ReferenceTargetIssue",
    "check_reference_targets",
    "find_reference_target_issues",
    "validate_fhir_reference_types",
    "validate_reference_targets",
    "validate_reference_types",
    "validate_observation_extensions",
    "FHIRClinicalExchangeWorkbench",
    "FHIRExchange",
    "FHIRExchangeError",
    "FHIRExchangeWorkbench",
    "FHIRValidationError",
    "build_clinical_document",
    "build_fhir_document",
    "build_ipa_example",
    "build_ipa_patient_access",
    "build_ips_patient_summary",
    "build_patient_summary",
    "deidentify_fhir",
    "deidentify_bundle",
    "export_bundle",
    "export_fhir",
    "import_bundle",
    "import_fhir",
    "validate_exchange",
    "BASE_R4_RESOURCE_TYPES",
    "ValidationFinding",
    "ValidationResult",
    "validate_bundle",
    "validate_resource",
    "ConformanceResult",
    "US_CORE_VERSION",
    "check_us_core",
    "FHIRBundle",
    "FHIRExportSummary",
]
