"""Evidence-bound normalization of heterogeneous clinical component outputs."""

from .normalization import (
    CLINICAL_FACT_NORMALIZATION_SCHEMA_VERSION,
    FACT_FIELD_STATES,
    FACT_FRAGMENT_KINDS,
    FACT_PROFILE_SPECS,
    NORMALIZER_VERSION,
    ClinicalFactNormalizer,
    ComponentOutputEnvelope,
    FactFragment,
    FactNormalizationError,
    FactNormalizationRequest,
    FactProfileSpec,
    MappingFactAdapter,
    NormalizedClinicalFact,
    RelationParticipant,
    load_clinical_fact_normalization_schema,
)
from .reconciliation import (
    FACT_CONFLICT_TYPES,
    FACT_GROUP_KINDS,
    FACT_RECONCILER_VERSION,
    FACT_RECONCILIATION_COMPATIBILITY_POLICY,
    FACT_RECONCILIATION_SCHEMA_VERSION,
    FactEquivalenceGroup,
    FactReconciler,
    FactReconciliationError,
    FactReconciliationInput,
    FactReconciliationPolicy,
    FactReconciliationResult,
    build_human_resolution,
    load_fact_reconciliation_schema,
    persist_fact_reconciliation,
)

__all__ = [
    "CLINICAL_FACT_NORMALIZATION_SCHEMA_VERSION",
    "FACT_FIELD_STATES",
    "FACT_FRAGMENT_KINDS",
    "FACT_PROFILE_SPECS",
    "FACT_CONFLICT_TYPES",
    "FACT_GROUP_KINDS",
    "FACT_RECONCILIATION_COMPATIBILITY_POLICY",
    "FACT_RECONCILIATION_SCHEMA_VERSION",
    "FACT_RECONCILER_VERSION",
    "NORMALIZER_VERSION",
    "ClinicalFactNormalizer",
    "ComponentOutputEnvelope",
    "FactFragment",
    "FactEquivalenceGroup",
    "FactNormalizationError",
    "FactNormalizationRequest",
    "FactProfileSpec",
    "FactReconciliationError",
    "FactReconciliationInput",
    "FactReconciliationPolicy",
    "FactReconciliationResult",
    "FactReconciler",
    "MappingFactAdapter",
    "NormalizedClinicalFact",
    "RelationParticipant",
    "build_human_resolution",
    "load_clinical_fact_normalization_schema",
    "load_fact_reconciliation_schema",
    "persist_fact_reconciliation",
]
