"""Human approval contracts for high-impact agent actions."""

from __future__ import annotations

from .tokens import (
    APPROVAL_NONCE_BYTES,
    APPROVAL_RECEIPT_SCHEMA_VERSION,
    APPROVAL_TOKEN_SCHEMA_VERSION,
    APPROVAL_TOKEN_SIGNATURE_ALGORITHM,
    DEFAULT_APPROVAL_LIFETIME_SECONDS,
    LEGACY_APPROVAL_TOKEN_SCHEMA_VERSION,
    MAX_APPROVAL_CLOCK_SKEW_SECONDS,
    MAX_APPROVAL_LIFETIME_SECONDS,
    ApprovalActionMismatchError,
    ApprovalAuthorization,
    ApprovalExpiredError,
    ApprovalKeyError,
    ApprovalKeyProvider,
    ApprovalLifetimeError,
    ApprovalNonceStore,
    ApprovalNonceStoreError,
    ApprovalNotYetValidError,
    ApprovalReceipt,
    ApprovalReplayError,
    ApprovalReviewerRoleMismatchError,
    ApprovalSignatureError,
    ApprovalToken,
    ApprovalTokenError,
    ApprovalTokenSigner,
    ApprovalTokenValidationError,
    ApprovalTokenVerifier,
    InMemoryApprovalNonceStore,
    MappingApprovalKeyProvider,
    dispatch_with_approval_token,
)

__all__ = [
    "ApprovalAuthorization",
    "DEFAULT_APPROVAL_LIFETIME_SECONDS",
    "MAX_APPROVAL_LIFETIME_SECONDS",
    "MAX_APPROVAL_CLOCK_SKEW_SECONDS",
    "LEGACY_APPROVAL_TOKEN_SCHEMA_VERSION",
    "ApprovalKeyError",
    "ApprovalKeyProvider",
    "ApprovalLifetimeError",
    "ApprovalNotYetValidError",
    "MappingApprovalKeyProvider",
    "APPROVAL_NONCE_BYTES",
    "APPROVAL_RECEIPT_SCHEMA_VERSION",
    "APPROVAL_TOKEN_SCHEMA_VERSION",
    "APPROVAL_TOKEN_SIGNATURE_ALGORITHM",
    "ApprovalActionMismatchError",
    "ApprovalExpiredError",
    "ApprovalNonceStore",
    "ApprovalNonceStoreError",
    "ApprovalReceipt",
    "ApprovalReplayError",
    "ApprovalReviewerRoleMismatchError",
    "ApprovalSignatureError",
    "ApprovalToken",
    "ApprovalTokenError",
    "ApprovalTokenSigner",
    "ApprovalTokenValidationError",
    "ApprovalTokenVerifier",
    "InMemoryApprovalNonceStore",
    "dispatch_with_approval_token",
]
