"""Synthetic training data generators."""

from .burned_in import (
    BACKGROUND_MODES,
    BURNED_IN_LABELS,
    DEFAULT_CANVAS_SIZE,
    DEFAULT_FONT_NAMES,
    DEFAULT_FONT_SIZES,
    BurnedInExample,
    BurnedInGenerator,
    BurnedInTextBox,
    generate_burned_in_example,
)
from .locale_phi import (
    LOCALE_PHI_LABELS,
    SUPPORTED_LOCALE_PHI_LANGUAGES,
    LocalePhiExample,
    LocalePhiGenerator,
    SyntheticPhiSpan,
    generate_locale_phi_examples,
)
from .offset_projection import (
    SpanAnnotation,
    SpanProjectionError,
    normalize_span_annotations,
    realign_translated_spans,
    span_corruption_count,
    validate_span_integrity,
)
from .translation_augment import (
    DEFAULT_TARGET_LANGUAGES,
    SYNTHETIC_SOURCE,
    DictionaryTranslator,
    ModelBackedTranslator,
    TranslationAugmentedExample,
    augment_span_annotated_examples,
    load_span_jsonl,
    write_augmented_jsonl,
)

__all__ = [
    "BACKGROUND_MODES",
    "BURNED_IN_LABELS",
    "DEFAULT_CANVAS_SIZE",
    "DEFAULT_FONT_NAMES",
    "DEFAULT_FONT_SIZES",
    "DEFAULT_TARGET_LANGUAGES",
    "LOCALE_PHI_LABELS",
    "SYNTHETIC_SOURCE",
    "SUPPORTED_LOCALE_PHI_LANGUAGES",
    "BurnedInExample",
    "BurnedInGenerator",
    "BurnedInTextBox",
    "DictionaryTranslator",
    "LocalePhiExample",
    "LocalePhiGenerator",
    "ModelBackedTranslator",
    "SpanAnnotation",
    "SpanProjectionError",
    "SyntheticPhiSpan",
    "TranslationAugmentedExample",
    "augment_span_annotated_examples",
    "generate_burned_in_example",
    "generate_locale_phi_examples",
    "load_span_jsonl",
    "normalize_span_annotations",
    "realign_translated_spans",
    "span_corruption_count",
    "validate_span_integrity",
    "write_augmented_jsonl",
]
