"""Local versioned-key lifecycle helpers for audit evidence.

The helper in this module keeps key custody in the calling process. It never
persists key material, performs network calls, or includes keys in metadata,
representations, or error messages.
"""

from __future__ import annotations

import re
import secrets
from collections.abc import Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from .audit import AuditReport

_MIN_KEY_BYTES = 32
_MIN_KEY_SIZE = 32
_MAX_KEY_SIZE = 4096
_PREFIX_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}")


@dataclass(frozen=True)
class KeyMetadata:
    """Non-secret metadata for one lifecycle-managed key."""

    key_id: str
    version: int
    state: Literal["active", "retired"]

    @property
    def active(self) -> bool:
        """Return whether this key is selected for new signatures."""

        return self.state == "active"

    def to_dict(self) -> dict[str, str | int]:
        """Serialize lifecycle metadata without key material."""

        return {
            "key_id": self.key_id,
            "version": self.version,
            "state": self.state,
        }


class KeyLifecycle:
    """Manage one active key plus retained verification keys offline.

    New signatures use only :attr:`active_key_id`. Rotation retires the prior
    key but retains it in memory so audit reports signed before rotation remain
    verifiable by their non-secret key identifier. Persistence and secret-store
    access remain caller responsibilities.

    Args:
        initial_key: Initial HMAC key material. At least 32 bytes are required.
        prefix: PHI-free identifier prefix used for generated versioned IDs.
        key_size: Number of bytes generated by later key rotations.
    """

    def __init__(
        self,
        initial_key: bytes | str,
        *,
        prefix: str = "openmed",
        key_size: int = _MIN_KEY_SIZE,
    ) -> None:
        self._prefix = _validate_prefix(prefix)
        self._key_size = _validate_key_size(key_size)
        self._keys: dict[str, bytes] = {}
        self._retired_key_ids: set[str] = set()
        self._active_key_id = ""
        self._version = 0
        self.rotate(_key_bytes(initial_key))

    @classmethod
    def generate(
        cls,
        *,
        prefix: str = "openmed",
        key_size: int = _MIN_KEY_SIZE,
    ) -> KeyLifecycle:
        """Create a lifecycle with a cryptographically random local key."""

        validated_size = _validate_key_size(key_size)
        return cls(
            secrets.token_bytes(validated_size),
            prefix=prefix,
            key_size=validated_size,
        )

    @classmethod
    def from_keys(
        cls,
        keys: Mapping[str, bytes | str],
        *,
        active_key_id: str,
        prefix: str = "openmed",
        key_size: int = _MIN_KEY_SIZE,
    ) -> KeyLifecycle:
        """Restore caller-owned active and retired keys from a trusted mapping.

        Every identifier must follow ``<prefix>-vNNNN``. All non-active keys
        are treated as retired and remain available only for verification.
        """

        validated_prefix = _validate_prefix(prefix)
        validated_size = _validate_key_size(key_size)
        if not keys:
            raise ValueError("at least one lifecycle key is required")

        restored: dict[str, bytes] = {}
        versions: dict[str, int] = {}
        for key_id, key in keys.items():
            version = _key_version(key_id, prefix=validated_prefix)
            material = _key_bytes(key)
            if material in restored.values():
                raise ValueError("lifecycle keys must contain distinct key material")
            restored[key_id] = material
            versions[key_id] = version

        if active_key_id not in restored:
            raise ValueError("active_key_id must identify a supplied key")

        lifecycle = cls.__new__(cls)
        lifecycle._prefix = validated_prefix
        lifecycle._key_size = validated_size
        lifecycle._keys = restored
        lifecycle._retired_key_ids = set(restored) - {active_key_id}
        lifecycle._active_key_id = active_key_id
        lifecycle._version = max(versions.values())
        return lifecycle

    @property
    def active_key_id(self) -> str:
        """Return the non-secret identifier used for new signatures."""

        return self._active_key_id

    @property
    def active_key(self) -> bytes:
        """Return active key material for an immediate cryptographic operation."""

        return self._keys[self._active_key_id]

    def rotate(self, key: bytes | str | None = None) -> KeyMetadata:
        """Select a new versioned key and retire the previously active key.

        Args:
            key: Caller-supplied key material. When omitted, a random key is
                generated locally with :mod:`secrets`.

        Returns:
            Non-secret metadata for the newly active key.
        """

        material = secrets.token_bytes(self._key_size) if key is None else key
        key_bytes = _key_bytes(material)
        next_version = self._version + 1
        key_id = f"{self._prefix}-v{next_version:04d}"
        if key_id in self._keys:
            raise ValueError("generated key identifier already exists")
        if key_bytes in self._keys.values():
            raise ValueError("new key material must differ from retained keys")

        if self._active_key_id:
            self._retired_key_ids.add(self._active_key_id)
        self._keys[key_id] = key_bytes
        self._active_key_id = key_id
        self._version = next_version
        return KeyMetadata(key_id=key_id, version=next_version, state="active")

    def retire(self, key_id: str) -> KeyMetadata:
        """Mark an inactive key as retained for verification only."""

        version = _key_version(key_id, prefix=self._prefix)
        if key_id not in self._keys:
            raise KeyError("unknown key id")
        if key_id == self._active_key_id:
            raise ValueError("rotate before retiring the active key")
        self._retired_key_ids.add(key_id)
        return KeyMetadata(key_id=key_id, version=version, state="retired")

    def resolve(self, key_id: str, *, allow_retired: bool = True) -> bytes:
        """Resolve key material by ID without exposing it in error messages."""

        _key_version(key_id, prefix=self._prefix)
        if key_id not in self._keys:
            raise KeyError("unknown key id")
        if key_id in self._retired_key_ids and not allow_retired:
            raise KeyError("retired key is unavailable for active use")
        return self._keys[key_id]

    def metadata(self) -> tuple[KeyMetadata, ...]:
        """Return version-ordered, key-free lifecycle metadata."""

        records = []
        for key_id in self._keys:
            version = _key_version(key_id, prefix=self._prefix)
            state: Literal["active", "retired"] = (
                "active" if key_id == self._active_key_id else "retired"
            )
            records.append(KeyMetadata(key_id=key_id, version=version, state=state))
        return tuple(sorted(records, key=lambda record: record.version))

    def sign_audit(self, report: AuditReport) -> AuditReport:
        """Sign an audit report with the active versioned key."""

        return report.sign(self.active_key, key_id=self.active_key_id)

    def verify_audit(
        self,
        report: AuditReport,
        *,
        original_text: str | None = None,
        deidentified_text: str | None = None,
    ) -> bool:
        """Verify an audit report using its active or retired key ID."""

        if report.signature is None:
            return False
        try:
            key = self.resolve(report.signature.key_id, allow_retired=True)
        except (KeyError, ValueError):
            return False
        return report.verify(
            key,
            original_text=original_text,
            deidentified_text=deidentified_text,
        )

    def __repr__(self) -> str:
        return (
            f"KeyLifecycle(prefix={self._prefix!r}, "
            f"active_key_id={self._active_key_id!r}, keys={len(self._keys)})"
        )


def _validate_prefix(prefix: str) -> str:
    if not isinstance(prefix, str) or _PREFIX_PATTERN.fullmatch(prefix) is None:
        raise ValueError("prefix must be a PHI-free identifier")
    return prefix


def _validate_key_size(key_size: int) -> int:
    if type(key_size) is not int or not _MIN_KEY_SIZE <= key_size <= _MAX_KEY_SIZE:
        raise ValueError("key_size must be an integer from 32 through 4096")
    return key_size


def _key_bytes(key: bytes | str) -> bytes:
    if isinstance(key, str):
        material = key.encode("utf-8")
    elif isinstance(key, bytes):
        material = key
    else:
        raise TypeError("key material must be str or bytes")
    if len(material) < _MIN_KEY_BYTES:
        raise ValueError("key material must contain at least 32 bytes")
    return material


def _key_version(key_id: str, *, prefix: str) -> int:
    if not isinstance(key_id, str):
        raise ValueError("key_id must be a versioned identifier")
    match = re.fullmatch(rf"{re.escape(prefix)}-v([0-9]{{4,}})", key_id)
    if match is None:
        raise ValueError("key_id must be a versioned identifier")
    version = int(match.group(1))
    if version < 1:
        raise ValueError("key_id version must be positive")
    if key_id != f"{prefix}-v{version:04d}":
        raise ValueError("key_id must use its canonical version form")
    return version
