"""Local-first compliance reporting, subject-access, and evidence helpers.

This package hosts local-first, access-logged compliance workflows built on the
surrogate vault, de-identification audit reports, and a tamper-evident audit
chain, plus deterministic technical control crosswalks for auditor handoff.
"""

from .audit_chain import (
    AuditRecord,
    AuditSink,
    HashChainAuditLog,
)
from .data_use import (
    DEFAULT_DATA_USE_POLICY,
    DEFAULT_DENIED_ACTIONS,
    DataUseAction,
    DataUseEvaluation,
    DataUsePolicy,
    DataUsePolicyViolation,
    DataUseTag,
    DataUseViolation,
    DataUseViolationError,
    TagViolationReport,
    normalize_data_use_actions,
    normalize_data_use_tags,
)
from .dsar import (
    DSAR_ADVISORY,
    ERASURE_PREVIEW_EVENT,
    EXPORT_EVENT,
    DsarEntry,
    DsarPackage,
    ErasurePlan,
    SubjectIdentifier,
    assemble_dsar_package,
    plan_erasure,
    render_dsar_summary,
)
from .iso27701 import (
    CONTROL_STATUSES,
    MANIFEST_FILENAME,
    MARKDOWN_FILENAME,
    ControlEvidence,
    ControlEvidencePack,
    ControlEvidencePackResult,
    EvidencePointer,
    build_control_evidence_pack,
    generate_control_evidence_pack,
    load_control_evidence_schema,
    render_control_evidence_markdown,
)
from .safe_harbor import (
    SAFE_HARBOR_ATTESTATION_NOTICE,
    SAFE_HARBOR_ATTESTATION_SCHEMA_VERSION,
    SAFE_HARBOR_CATEGORY_LABELS,
    SAFE_HARBOR_CATEGORY_ORDER,
    SAFE_HARBOR_POLICY,
    SafeHarborAttestation,
    SafeHarborCategoryAttestation,
    generate_safe_harbor_attestation,
)

__all__ = [
    "AuditRecord",
    "AuditSink",
    "HashChainAuditLog",
    "DEFAULT_DATA_USE_POLICY",
    "DEFAULT_DENIED_ACTIONS",
    "DataUseAction",
    "DataUseEvaluation",
    "DataUsePolicy",
    "DataUsePolicyViolation",
    "DataUseTag",
    "DataUseViolation",
    "DataUseViolationError",
    "TagViolationReport",
    "normalize_data_use_actions",
    "normalize_data_use_tags",
    "DSAR_ADVISORY",
    "EXPORT_EVENT",
    "ERASURE_PREVIEW_EVENT",
    "SubjectIdentifier",
    "DsarEntry",
    "DsarPackage",
    "ErasurePlan",
    "assemble_dsar_package",
    "render_dsar_summary",
    "plan_erasure",
    "CONTROL_STATUSES",
    "MANIFEST_FILENAME",
    "MARKDOWN_FILENAME",
    "ControlEvidence",
    "ControlEvidencePack",
    "ControlEvidencePackResult",
    "EvidencePointer",
    "build_control_evidence_pack",
    "generate_control_evidence_pack",
    "load_control_evidence_schema",
    "render_control_evidence_markdown",
    "SAFE_HARBOR_ATTESTATION_NOTICE",
    "SAFE_HARBOR_ATTESTATION_SCHEMA_VERSION",
    "SAFE_HARBOR_CATEGORY_LABELS",
    "SAFE_HARBOR_CATEGORY_ORDER",
    "SAFE_HARBOR_POLICY",
    "SafeHarborAttestation",
    "SafeHarborCategoryAttestation",
    "generate_safe_harbor_attestation",
]
