"""Standardized OpenMed training recipes."""

from importlib import import_module
from typing import Any

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "CLINICAL_PRIVACY_CHECKPOINT_NAME",
    "CLINICAL_PRIVACY_CHECKPOINT_SCHEMA_VERSION",
    "CLINICAL_PRIVACY_CONTRACT_REF",
    "CLINICAL_PRIVACY_FAMILY",
    "CLINICAL_PRIVACY_OBJECTIVE",
    "CLINICAL_PRIVACY_RECIPE_REF",
    "CLINICAL_PRIVACY_TIER0_CONTRACT",
    "CLINICAL_PRIVACY_TRAINING_SCHEMA_VERSION",
    "CLINICAL_PRIVACY_TRAINING_SOURCE_IDS",
    "DAPT_CORPUS_MANIFEST_PATH",
    "DAPT_CORPUS_SCHEMA_VERSION",
    "MAX_LORA_TRAINABLE_RATIO",
    "PRESET_BY_MODE",
    "QLORA_CONFIG_SCHEMA_VERSION",
    "QLORA_SMOKE_PRESET",
    "QLORA_SMOKE_RESULT_SCHEMA_VERSION",
    "AdjudicationCandidate",
    "AdjudicationItem",
    "AdjudicationQueue",
    "ActiveLearningCandidate",
    "ActiveLearningQueue",
    "CRITICAL_LABELS",
    "CorpusManifestError",
    "ClinicalPrivacyCheckpointManifest",
    "ClinicalPrivacyGateThreshold",
    "ClinicalPrivacySourceBinding",
    "ClinicalPrivacyTrainingError",
    "ClinicalPrivacyTrainingPlan",
    "ClinicalPrivacyTier0Contract",
    "DaptCorpusAssemblyResult",
    "DryRunResult",
    "DIRECTID_CONTRACT_REF",
    "DIRECTID_CANDIDATE_FORMAT",
    "DIRECTID_CANDIDATE_REPO_ID",
    "DIRECTID_CANDIDATE_SCHEMA_VERSION",
    "DIRECTID_DISTILLATION_SCHEMA_VERSION",
    "DIRECTID_DATASET_EVIDENCE_SCHEMA_VERSION",
    "DIRECTID_DATASET_MANIFEST_ID",
    "DIRECTID_DATASET_MANIFEST_REF",
    "DIRECTID_DATASET_SCHEMA_VERSION",
    "DIRECTID_FAMILY",
    "DIRECTID_GATE_CODES",
    "DIRECTID_MODE_A_PIPELINE_REF",
    "DIRECTID_REQUIRED_ID_SUBTYPES",
    "DIRECTID_RUN_MANIFEST_SCHEMA_VERSION",
    "DIRECTID_TRAINING_REPORT_SCHEMA_VERSION",
    "DIRECTID_TINY_HEAD_CONTRACT",
    "DirectIDBatchEvidence",
    "DirectIDCandidateCheckpoint",
    "DirectIDContractError",
    "DirectIDDatasetError",
    "DirectIDDatasetManifest",
    "DirectIDDatasetSource",
    "DirectIDDistillationError",
    "DirectIDHardNegativeOutcome",
    "DirectIDHeadContract",
    "DirectIDLabelOutcome",
    "DirectIDPresetValidation",
    "DirectIDRunArtifacts",
    "DirectIDRunContext",
    "DirectIDSplitEvidence",
    "DirectIDSplitManifest",
    "DirectIDSyntheticSettings",
    "DirectIDTrainer",
    "DirectIDTrainingOutput",
    "GatedCorpusAccessError",
    "DistillationReport",
    "DistillationTargets",
    "EntityTypeWeights",
    "HARD_NEGATIVE_CATEGORIES",
    "HardNegativeExample",
    "HardNegativeGenerator",
    "HardNegativeSampler",
    "JsonlPassageSource",
    "KDLossBreakdown",
    "LabeledSpan",
    "LabelRecallDelta",
    "MimicIIIDuaSource",
    "ModeADistillationPipeline",
    "NetworkEgressBlockedError",
    "Passage",
    "PassageSource",
    "PUBLIC_DAPT_SOURCES",
    "QloraAdapterConfig",
    "QloraBaseModelConfig",
    "QloraDataConfig",
    "QloraEntityDelta",
    "QloraEvidenceConfig",
    "QloraGateConfig",
    "QloraRecipeConfig",
    "QloraSmokeResult",
    "RecordPassageSource",
    "RecipeConfigError",
    "RepairedSpan",
    "SpanAgreementBreakdown",
    "TrainingRecipeConfig",
    "WeakLabelDecision",
    "WeakLabelSpan",
    "arxiv_qbio_source",
    "assemble_dapt_corpus",
    "assert_manifest_has_no_raw_text",
    "build_distillation_report",
    "build_clinical_privacy_checkpoint_manifest",
    "build_directid_dataset_evidence",
    "config_hash",
    "corpus_manifest_hash",
    "count_hard_negatives",
    "compute_kd_loss",
    "compute_span_agreement_loss",
    "decode_repaired_spans",
    "directid_dataset_manifest_hash",
    "directid_records_hash",
    "directid_source_manifest_hash",
    "directid_synthetic_settings_hash",
    "dry_run_recipe",
    "gate_requirements_by_code",
    "generate_directid_hard_negatives",
    "load_corpus_manifest",
    "load_directid_dataset_manifest",
    "load_preset",
    "load_qlora_preset",
    "make_adjudication_item",
    "manifest_row_for_passage",
    "normalize_passage_text",
    "normalize_weak_span",
    "pmc_abstract_source",
    "prepare_directid_batch",
    "pubmed_abstract_source",
    "requires_hard_negative_sampler",
    "resolve_clinical_privacy_training_plan",
    "run_directid_tiny_distillation",
    "run_recipe",
    "run_qlora_smoke",
    "runtime_dependencies",
    "sample_hard_negatives",
    "sampler_for_recipe",
    "soft_label_distributions",
    "span_logits_from_repaired_spans",
    "student_backbone_from_tiny_distill_preset",
    "token_count",
    "validate_clinical_privacy_checkpoint_manifest",
    "validate_directid_contract",
    "validate_directid_batch",
    "validate_directid_dataset_manifest",
    "validate_directid_preset",
    "validate_directid_split_records",
    "weak_label_document",
    "write_clinical_privacy_checkpoint_manifest",
]


def __getattr__(name: str) -> Any:
    if name in {
        "CLINICAL_PRIVACY_CHECKPOINT_NAME",
        "CLINICAL_PRIVACY_CHECKPOINT_SCHEMA_VERSION",
        "CLINICAL_PRIVACY_CONTRACT_REF",
        "CLINICAL_PRIVACY_FAMILY",
        "CLINICAL_PRIVACY_OBJECTIVE",
        "CLINICAL_PRIVACY_RECIPE_REF",
        "CLINICAL_PRIVACY_TIER0_CONTRACT",
        "CLINICAL_PRIVACY_TRAINING_SCHEMA_VERSION",
        "CLINICAL_PRIVACY_TRAINING_SOURCE_IDS",
        "ClinicalPrivacyCheckpointManifest",
        "ClinicalPrivacyGateThreshold",
        "ClinicalPrivacySourceBinding",
        "ClinicalPrivacyTrainingError",
        "ClinicalPrivacyTrainingPlan",
        "ClinicalPrivacyTier0Contract",
        "build_clinical_privacy_checkpoint_manifest",
        "resolve_clinical_privacy_training_plan",
        "validate_clinical_privacy_checkpoint_manifest",
        "write_clinical_privacy_checkpoint_manifest",
    }:
        clinical_privacy = import_module(".clinical_privacy", __name__)
        return getattr(clinical_privacy, name)
    if name in {
        "CONFIG_SCHEMA_VERSION",
        "MAX_LORA_TRAINABLE_RATIO",
        "PRESET_BY_MODE",
        "QLORA_CONFIG_SCHEMA_VERSION",
        "QLORA_SMOKE_PRESET",
        "QLORA_SMOKE_RESULT_SCHEMA_VERSION",
        "DryRunResult",
        "NetworkEgressBlockedError",
        "QloraAdapterConfig",
        "QloraBaseModelConfig",
        "QloraDataConfig",
        "QloraEntityDelta",
        "QloraEvidenceConfig",
        "QloraGateConfig",
        "QloraRecipeConfig",
        "QloraSmokeResult",
        "RecipeConfigError",
        "TrainingRecipeConfig",
        "config_hash",
        "dry_run_recipe",
        "load_preset",
        "load_qlora_preset",
        "run_recipe",
        "run_qlora_smoke",
        "runtime_dependencies",
    }:
        recipe = import_module(".recipe", __name__)
        return getattr(recipe, name)
    if name in {
        "DAPT_CORPUS_MANIFEST_PATH",
        "DAPT_CORPUS_SCHEMA_VERSION",
        "CorpusManifestError",
        "DaptCorpusAssemblyResult",
        "GatedCorpusAccessError",
        "JsonlPassageSource",
        "MimicIIIDuaSource",
        "Passage",
        "PassageSource",
        "PUBLIC_DAPT_SOURCES",
        "RecordPassageSource",
        "arxiv_qbio_source",
        "assemble_dapt_corpus",
        "assert_manifest_has_no_raw_text",
        "corpus_manifest_hash",
        "load_corpus_manifest",
        "manifest_row_for_passage",
        "normalize_passage_text",
        "pmc_abstract_source",
        "pubmed_abstract_source",
        "token_count",
    }:
        corpus = import_module(".corpus", __name__)
        return getattr(corpus, name)
    if name in {
        "DIRECTID_CONTRACT_REF",
        "DIRECTID_FAMILY",
        "DIRECTID_GATE_CODES",
        "DIRECTID_REQUIRED_ID_SUBTYPES",
        "DIRECTID_TINY_HEAD_CONTRACT",
        "DirectIDContractError",
        "DirectIDHeadContract",
        "DirectIDPresetValidation",
        "gate_requirements_by_code",
        "validate_directid_contract",
        "validate_directid_preset",
    }:
        directid = import_module(".directid", __name__)
        return getattr(directid, name)
    if name in {
        "DIRECTID_CANDIDATE_FORMAT",
        "DIRECTID_CANDIDATE_REPO_ID",
        "DIRECTID_CANDIDATE_SCHEMA_VERSION",
        "DIRECTID_DISTILLATION_SCHEMA_VERSION",
        "DIRECTID_MODE_A_PIPELINE_REF",
        "DIRECTID_RUN_MANIFEST_SCHEMA_VERSION",
        "DIRECTID_TRAINING_REPORT_SCHEMA_VERSION",
        "DirectIDCandidateCheckpoint",
        "DirectIDDistillationError",
        "DirectIDHardNegativeOutcome",
        "DirectIDLabelOutcome",
        "DirectIDRunArtifacts",
        "DirectIDRunContext",
        "DirectIDTrainer",
        "DirectIDTrainingOutput",
        "run_directid_tiny_distillation",
    }:
        directid_distill = import_module(".directid_distill", __name__)
        return getattr(directid_distill, name)
    if name in {
        "DIRECTID_DATASET_EVIDENCE_SCHEMA_VERSION",
        "DIRECTID_DATASET_MANIFEST_ID",
        "DIRECTID_DATASET_MANIFEST_REF",
        "DIRECTID_DATASET_SCHEMA_VERSION",
        "DirectIDBatchEvidence",
        "DirectIDDatasetError",
        "DirectIDDatasetManifest",
        "DirectIDDatasetSource",
        "DirectIDSplitEvidence",
        "DirectIDSplitManifest",
        "DirectIDSyntheticSettings",
        "build_directid_dataset_evidence",
        "directid_dataset_manifest_hash",
        "directid_records_hash",
        "directid_source_manifest_hash",
        "directid_synthetic_settings_hash",
        "generate_directid_hard_negatives",
        "load_directid_dataset_manifest",
        "prepare_directid_batch",
        "validate_directid_batch",
        "validate_directid_dataset_manifest",
        "validate_directid_split_records",
    }:
        directid_dataset = import_module(".directid_dataset", __name__)
        return getattr(directid_dataset, name)
    if name in {
        "HARD_NEGATIVE_CATEGORIES",
        "HardNegativeExample",
        "HardNegativeGenerator",
        "HardNegativeSampler",
        "count_hard_negatives",
        "requires_hard_negative_sampler",
        "sample_hard_negatives",
        "sampler_for_recipe",
    }:
        hard_negatives = import_module(".hard_negatives", __name__)
        return getattr(hard_negatives, name)
    if name in {
        "ActiveLearningCandidate",
        "ActiveLearningQueue",
        "CRITICAL_LABELS",
    }:
        active_learning = import_module(".active_learning", __name__)
        return getattr(active_learning, name)
    if name in {
        "AdjudicationCandidate",
        "AdjudicationItem",
        "AdjudicationQueue",
        "make_adjudication_item",
    }:
        adjudication = import_module(".adjudication", __name__)
        return getattr(adjudication, name)
    if name in {
        "DistillationReport",
        "DistillationTargets",
        "EntityTypeWeights",
        "KDLossBreakdown",
        "LabeledSpan",
        "LabelRecallDelta",
        "ModeADistillationPipeline",
        "RepairedSpan",
        "SpanAgreementBreakdown",
        "build_distillation_report",
        "compute_kd_loss",
        "compute_span_agreement_loss",
        "decode_repaired_spans",
        "soft_label_distributions",
        "span_logits_from_repaired_spans",
        "student_backbone_from_tiny_distill_preset",
    }:
        distill = import_module(".distill", __name__)
        return getattr(distill, name)
    if name in {
        "WeakLabelDecision",
        "WeakLabelSpan",
        "normalize_weak_span",
        "weak_label_document",
    }:
        weak_labeling = import_module(".weak_labeling", __name__)
        return getattr(weak_labeling, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
